(function(){Array.prototype.forEach||(Array.prototype.forEach=function(a,c){var b=this.length;if("function"!=typeof a)throw new TypeError;for(var d=0;d<b;d++)d in this&&a.call(c,this[d],d,this)})})();(function(){Array.prototype.findFirst||(Array.prototype.findFirst=function(a){if("function"===typeof a)for(var c=0;c<this.length;c++)if(c in this&&a(this[c]))return this[c]})})();(function(){"object"!==typeof console&&(console={log:function(){}})})();var MazeGlobals=function(){return{PROP_HEIGHT:64,PROJECTIONPLANEWIDTH:320,PROJECTIONPLANEHEIGHT:200,PROJECTIONPLANE_WIDTHTIMESHEIGHT:64E3,TEXTBOXWIDTH:320,TEXTBOXHEIGHT:200,TILE_SIZE:64,TILE_SIZE_SHIFT:6,PLAYER_DIST_TO_PROJ_PLANE:277,MAZE_DIR:"MazeDir"}}();Trig=function(){this.createTables()};Trig.prototype.ANGLE60=MazeGlobals.PROJECTIONPLANEWIDTH;Trig.prototype.ANGLE30=Math.round(Trig.prototype.ANGLE60/2);Trig.prototype.ANGLE90=Math.round(3*Trig.prototype.ANGLE30);Trig.prototype.ANGLE180=Math.round(2*Trig.prototype.ANGLE90);Trig.prototype.ANGLE270=Math.round(3*Trig.prototype.ANGLE90);Trig.prototype.ANGLE360=Math.round(6*Trig.prototype.ANGLE60);Trig.prototype.ANGLE0=0;Trig.prototype.ANGLE5=Math.round(Trig.prototype.ANGLE30/6);
Trig.prototype.ANGLE10=2*Trig.prototype.ANGLE5;Trig.prototype.ANGLE45=Trig.prototype.ANGLE5+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10;Trig.prototype.ANGLE135=Trig.prototype.ANGLE90+Trig.prototype.ANGLE45;Trig.prototype.ANGLE225=Trig.prototype.ANGLE180+Trig.prototype.ANGLE45;Trig.prototype.ANGLE315=Trig.prototype.ANGLE270+Trig.prototype.ANGLE45;Trig.prototype.ANGLE85=Trig.prototype.ANGLE90-Trig.prototype.ANGLE5;
Trig.prototype.ANGLE95=Trig.prototype.ANGLE90+Trig.prototype.ANGLE5;Trig.prototype.ANGLE265=Trig.prototype.ANGLE270-Trig.prototype.ANGLE5;Trig.prototype.ANGLE275=Trig.prototype.ANGLE270+Trig.prototype.ANGLE5;Trig.prototype.ANGLE355=Trig.prototype.ANGLE360-Trig.prototype.ANGLE5;Trig.prototype.ANGLE175=Trig.prototype.ANGLE180-Trig.prototype.ANGLE5;Trig.prototype.ANGLE185=Trig.prototype.ANGLE180+Trig.prototype.ANGLE5;Trig.prototype.sinTable=[];Trig.prototype.iSinTable=[];Trig.prototype.cosTable=[];
Trig.prototype.iCosTable=[];Trig.prototype.tanTable=[];Trig.prototype.iTanTable=[];Trig.prototype.fishTable=[];Trig.prototype.xStepTable=[];Trig.prototype.yStepTable=[];
Trig.prototype.createTables=function(){var a=0,c=0;this.sinTable=Array(this.ANGLE360+1);this.iSinTable=Array(this.ANGLE360+1);this.cosTable=Array(this.ANGLE360+1);this.iCosTable=Array(this.ANGLE360+1);this.tanTable=Array(this.ANGLE360+1);this.iTanTable=Array(this.ANGLE360+1);this.fishTable=Array(this.ANGLE60+1);this.xStepTable=Array(this.ANGLE360+1);this.yStepTable=Array(this.ANGLE360+1);for(a=0;a<=this.ANGLE360;a++)c=this.arcToRad(a)+1E-4,this.sinTable[a]=Math.sin(c),this.iSinTable[a]=1/this.sinTable[a],
this.cosTable[a]=Math.cos(c),this.iCosTable[a]=1/this.cosTable[a],this.tanTable[a]=Math.tan(c),this.iTanTable[a]=1/this.tanTable[a],a>=this.ANGLE90&&a<this.ANGLE270?(this.xStepTable[a]=1*MazeGlobals.TILE_SIZE/this.tanTable[a],0<this.xStepTable[a]&&(this.xStepTable[a]=-this.xStepTable[a])):(this.xStepTable[a]=1*MazeGlobals.TILE_SIZE/this.tanTable[a],0>this.xStepTable[a]&&(this.xStepTable[a]=-this.xStepTable[a])),a>=this.ANGLE0&&a<this.ANGLE180?(this.yStepTable[a]=1*MazeGlobals.TILE_SIZE*this.tanTable[a],
0>this.yStepTable[a]&&(this.yStepTable[a]=-this.yStepTable[a])):(this.yStepTable[a]=1*MazeGlobals.TILE_SIZE*this.tanTable[a],0<this.yStepTable[a]&&(this.yStepTable[a]=-this.yStepTable[a]));for(a=-this.ANGLE30;a<=this.ANGLE30;a++)c=this.arcToRad(a),this.fishTable[a+this.ANGLE30]=1/Math.cos(c)};Trig.prototype.arcToRad=function(a){return 1*a*Math.PI/this.ANGLE180};Trig.degreesToMazeAngleUnits=function(a){return~~(MazeGlobals.PROJECTIONPLANEWIDTH*a/60)};Trig.radToDegrees=function(a){return 180*a/Math.PI};if(null==Dest||"object"!=typeof Dest)var Dest={};
Dest=function(){this.angle=this.yPos=this.xPos=0;this.backgroundFromFile=this.useExistingAngle=!1;this.backgroundFromRGB=!0;this.useExistingBackground=!1;this.backgroundFile="";this.skyRed=40;this.skyGreen=125;this.skyBlue=225;this.skyRedStep=2;this.skyBlueStep=this.skyGreenStep=0;this.groundRed=100;this.groundGreen=80;this.groundBlue=40;this.groundBlueStep=this.groundGreenStep=this.groundRedStep=1;this.landscapeFile=this.useExistingLandscape=this.usingALandscape=!1;this.landscapeStartAngle=this.landscapeOffsetFromTop=
0};if(null==Trap||"object"!=typeof Trap)var Trap={};Trap=function(){this.bottomSide=this.topSide=this.rightSide=this.leftSide=0;this.usingDest=!1;this.gotoDest=0;this.usingOverlay=!1;this.overlayFile="";this.overlayPixels=null;this.usingSound=!1;this.soundFile=""};Trap.prototype.insideThisTrap=function(a,c){return a>=this.leftSide&&a<=this.rightSide&&c>=this.topSide&&c<=this.bottomSide};if(null==GeneralConfig||"object"!=typeof GeneralConfig)var GeneralConfig={};GeneralConfig=function(a,c,b){GeneralConfig.MAUTH_VER_NUM="1.3";GeneralConfig.FULL_MAUTH_VER_NUM="01.30";this.document=a;this.mazeId=c;this.textAreaBox=b};GeneralConfig.prototype.GENERAL_CONFIG_INI_FILE="GeneralConfig.ini";GeneralConfig.prototype.openingCreditImg=null;GeneralConfig.prototype.titleLine1=null;GeneralConfig.prototype.titleLine2=null;GeneralConfig.prototype.titleLine3=null;GeneralConfig.prototype.titleLine4=null;
GeneralConfig.prototype.line1Clr=null;GeneralConfig.prototype.line2Clr=null;GeneralConfig.prototype.line3Clr=null;GeneralConfig.prototype.line4Clr=null;GeneralConfig.prototype.yPosLine1=null;GeneralConfig.prototype.yPosLine2=null;GeneralConfig.prototype.yPosLine3=null;GeneralConfig.prototype.yPosLine4=null;GeneralConfig.prototype.fontSizeLine1=null;GeneralConfig.prototype.fontSizeLine2=null;GeneralConfig.prototype.fontSizeLine3=null;GeneralConfig.prototype.fontSizeLine4=null;
GeneralConfig.prototype.backGroundClr=null;GeneralConfig.prototype.textClr=null;GeneralConfig.prototype.usingBackroundMusic=null;
GeneralConfig.prototype.loadConfigFile=function(a){var c="undefined"!=typeof a,b=new IniFile(this.mazeId,this.GENERAL_CONFIG_INI_FILE),d=this;b.loadFile(function(e,g){if(e){console.log("GeneralConfig.js: GeneralConfig.ini successfully loaded.");d.iniObj=b.iniObj;var f=d.iniObj.General.Ver;f!=GeneralConfig.MAUTH_VER_NUM&&console.log("GeneralConfig.js: GeneralConfig.ini file may be out of date. Expected version: "+GeneralConfig.MAUTH_VER_NUM+"Version found: "+f);c&&a(!0)}else d.textAreaBox.dumpError("error: "+
g),c&&a(!1,g)})};
GeneralConfig.prototype.loadAssociatedImages=function(a){var c="undefined"!=typeof a;GeneralConfig.prototype.titleLine1=this.iniObj.OpeningCredits.TitleLine1;GeneralConfig.prototype.titleLine2=this.iniObj.OpeningCredits.TitleLine2;GeneralConfig.prototype.titleLine3=this.iniObj.OpeningCredits.TitleLine3;GeneralConfig.prototype.titleLine4=this.iniObj.OpeningCredits.TitleLine4;GeneralConfig.prototype.line1Clr=this.iniObj.OpeningCredits.ColorLine1;GeneralConfig.prototype.line2Clr=this.iniObj.OpeningCredits.ColorLine2;GeneralConfig.prototype.line3Clr=
this.iniObj.OpeningCredits.ColorLine3;GeneralConfig.prototype.line4Clr=this.iniObj.OpeningCredits.ColorLine4;GeneralConfig.prototype.yPosLine1=this.iniObj.OpeningCredits.YPosLine1;GeneralConfig.prototype.yPosLine2=this.iniObj.OpeningCredits.YPosLine2;GeneralConfig.prototype.yPosLine3=this.iniObj.OpeningCredits.YPosLine3;GeneralConfig.prototype.yPosLine4=this.iniObj.OpeningCredits.YPosLine4;GeneralConfig.prototype.fontSizeLine1=this.iniObj.OpeningCredits.FontSizeLine1;GeneralConfig.prototype.fontSizeLine2=
this.iniObj.OpeningCredits.FontSizeLine2;GeneralConfig.prototype.fontSizeLine3=this.iniObj.OpeningCredits.FontSizeLine3;GeneralConfig.prototype.fontSizeLine4=this.iniObj.OpeningCredits.FontSizeLine4;null==GeneralConfig.prototype.titleLine1&&(GeneralConfig.prototype.titleLine1="");null==GeneralConfig.prototype.titleLine2&&(GeneralConfig.prototype.titleLine2="");null==GeneralConfig.prototype.titleLine3&&(GeneralConfig.prototype.titleLine3="");null==GeneralConfig.prototype.titleLine4&&(GeneralConfig.prototype.titleLine4=
"");null==GeneralConfig.prototype.line1Clr&&(GeneralConfig.prototype.line1Clr="gray");null==GeneralConfig.prototype.line2Clr&&(GeneralConfig.prototype.line2Clr="gray");null==GeneralConfig.prototype.line3Clr&&(GeneralConfig.prototype.line3Clr="gray");null==GeneralConfig.prototype.line4Clr&&(GeneralConfig.prototype.line4Clr="gray");null==GeneralConfig.prototype.yPosLine1&&(GeneralConfig.prototype.yPosLine1=58);null==GeneralConfig.prototype.yPosLine2&&(GeneralConfig.prototype.yPosLine2=84);null==GeneralConfig.prototype.yPosLine3&&
(GeneralConfig.prototype.yPosLine3=111);null==GeneralConfig.prototype.yPosLine4&&(GeneralConfig.prototype.yPosLine4=140);null==GeneralConfig.prototype.fontSizeLine1&&(GeneralConfig.prototype.fontSizeLine1=22);null==GeneralConfig.prototype.fontSizeLine2&&(GeneralConfig.prototype.fontSizeLine2=16);null==GeneralConfig.prototype.fontSizeLine3&&(GeneralConfig.prototype.fontSizeLine3=16);null==GeneralConfig.prototype.fontSizeLine4&&(GeneralConfig.prototype.fontSizeLine4=16);GeneralConfig.prototype.line1Clr=
GeneralConfig.prototype.line1Clr.toLowerCase();GeneralConfig.prototype.line2Clr=GeneralConfig.prototype.line2Clr.toLowerCase();GeneralConfig.prototype.line3Clr=GeneralConfig.prototype.line3Clr.toLowerCase();GeneralConfig.prototype.line4Clr=GeneralConfig.prototype.line4Clr.toLowerCase();var b=new ImageCanvas(this.document,this.mazeId,this.iniObj.OpeningCredits.OpeningCredits,MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT),d=this;b.loadFile(function(e,g){!1===e&&console.log(g);d.openingCreditImg=
b;c&&a(!0)})};if(null==OpeningCredits||"object"!=typeof OpeningCredits)var OpeningCredits={};OpeningCredits=function(a){OpeningCredits.STOP_WATCH_DURATION=4500;this.generalConfig=a;this.startTime=-1};
OpeningCredits.prototype.drawOpeningCredits=function(a){for(var c=a.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT),b=this.generalConfig.openingCreditImg,d=0;d<MazeGlobals.PROJECTIONPLANEHEIGHT;d++)for(var e=0;e<MazeGlobals.PROJECTIONPLANEWIDTH;e++){var g=4*(e+d*MazeGlobals.PROJECTIONPLANEWIDTH),f=b.imageData.data[g+1],h=b.imageData.data[g+2],k=4*(e+d*c.width);c.data[k+0]=b.imageData.data[g+0];c.data[k+1]=f;c.data[k+2]=h;c.data[k+3]=255}a.putImageData(c,0,0);a.font=
""+this.generalConfig.fontSizeLine1+"px Arial";a.fillStyle=""+this.generalConfig.line1Clr;c=a.measureText(this.generalConfig.titleLine1);c=c.width;c=MazeGlobals.PROJECTIONPLANEWIDTH/2-c/2;a.fillText(this.generalConfig.titleLine1,c,this.generalConfig.yPosLine1);a.font=""+this.generalConfig.fontSizeLine2+"px Arial";a.fillStyle=""+this.generalConfig.line2Clr;c=a.measureText(this.generalConfig.titleLine2);c=c.width;c=MazeGlobals.PROJECTIONPLANEWIDTH/2-c/2;a.fillText(this.generalConfig.titleLine2,c,this.generalConfig.yPosLine2);
a.font=""+this.generalConfig.fontSizeLine3+"px Arial";a.fillStyle=""+this.generalConfig.line3Clr;c=a.measureText(this.generalConfig.titleLine3);c=c.width;c=MazeGlobals.PROJECTIONPLANEWIDTH/2-c/2;a.fillText(this.generalConfig.titleLine3,c,this.generalConfig.yPosLine3);a.font=""+this.generalConfig.fontSizeLine4+"px Arial";a.fillStyle=""+this.generalConfig.line4Clr;c=a.measureText(this.generalConfig.titleLine4);c=c.width;c=MazeGlobals.PROJECTIONPLANEWIDTH/2-c/2;a.fillText(this.generalConfig.titleLine4,
c,this.generalConfig.yPosLine4)};OpeningCredits.prototype.startTheStopWatch=function(){this.startTime=(new Date).getTime()};OpeningCredits.prototype.getStopWatchTimeRemaining=function(){if(-1===this.startTime)return OpeningCredits.STOP_WATCH_DURATION;var a=(new Date).getTime()-this.startTime;return a>OpeningCredits.STOP_WATCH_DURATION?0:OpeningCredits.STOP_WATCH_DURATION-a};if(null==MazeConfig||"object"!=typeof MazeConfig)var MazeConfig={};MazeConfig=function(a,c,b,d,e){this.document=a;this.mazeId=c;this.textAreaBox=b;this.mapHeight=d;this.mapWidth=e;this.numTraps=0;this.numDests=1;this.traps=[];this.dests=[];this.iniObj={}};MazeConfig.prototype.MAZE_CONFIG_INI_FILE="MazeConfig.ini";
MazeConfig.prototype.loadConfigFile=function(a){var c="undefined"!=typeof a,b=new IniFile(this.mazeId,this.MAZE_CONFIG_INI_FILE),d=this;b.loadFile(function(e,g){if(e){console.log("MazeConfig.js: MazeConfig.ini successfully loaded.");d.iniObj=b.iniObj;var f=d.iniObj.General.Ver;f!=GeneralConfig.MAUTH_VER_NUM&&console.log("MazeConfig.js: MazeConfig.ini file may be out of date. Expected version: "+GeneralConfig.MAUTH_VER_NUM+"Version found: "+f);d.numTraps=d.iniObj.General.NumTraps;d.numDests=d.iniObj.General.NumDests;
0>=d.numTraps&&d.textAreaBox.dumpError("Number of destinations ('NumDests') in MazeConfig.ini file is zero.  You must have at least one for starting coordinates.");for(f=0;f<d.numDests;f++)d.dests.push(d.getDest(f,d.mapWidth,d.mapHeight));for(f=0;f<d.numTraps;f++)d.traps.push(d.getTrap(f,d.mapWidth,d.mapHeight,d.numDests));c&&a(!0)}else d.textAreaBox.dumpError("error: "+g),c&&a(!1,g)})};
MazeConfig.prototype.insideATrap=function(a,c){for(var b=0;b<this.traps.length;b++){var d=this.traps[b];if(d.insideThisTrap(a,c))return d}return null};MazeConfig.prototype.advanceToDest=function(a){return 0<=a&&a<this.numDests?this.dests[a]:null};
MazeConfig.prototype.getTrap=function(a,c,b,d){var e=new Trap;a="Trap"+a;var g=this.getValueCheckingRange(a,"LeftTile",15,0,this.mapWidth-1,"This constraint is based upon the map width.");c=this.getValueCheckingRange(a,"RightTile",16,0,c-1,"This constraint is based upon the map width.");var f=this.getValueCheckingRange(a,"TopTile",15,0,b-1,"This constraint is based upon the map height.");b=this.getValueCheckingRange(a,"BottomTile",16,0,b-1,"This constraint is based upon the map height.");var h=this.getValueCheckingRange(a,
"LeftTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),k=this.getValueCheckingRange(a,"RightTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),l=this.getValueCheckingRange(a,"TopTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),m=this.getValueCheckingRange(a,"BottomTileOffset",0,0,MazeGlobals.TILE_SIZE-1,"");e.leftSide=parseInt(g,10)*MazeGlobals.TILE_SIZE+parseInt(h,10);e.rightSide=parseInt(c,10)*MazeGlobals.TILE_SIZE+parseInt(k,10);e.topSide=parseInt(f,10)*MazeGlobals.TILE_SIZE+parseInt(l,10);e.bottomSide=parseInt(b,
10)*MazeGlobals.TILE_SIZE+parseInt(m,10);e.gotoDest=this.getValueCheckingRange(a,"GotoDest",-1,0,d-1,"");e.usingDest=-1!=e.gotoDest;e.usingSound=!1;e.soundFile=this.iniObj[a].SoundEffect;null===e.soundFile&&(e.soundFile="");e.overlayFile=this.iniObj[a].Overlay;null==e.overlayFile&&(e.overlayFile="");e.usingOverlay=0<e.overlayFile.length;return e};
MazeConfig.prototype.getDest=function(a,c,b){c=new Dest;b="Dest"+a;var d=this.getValueCheckingRange(b,"XTile",10,0,this.mapWidth-1,"This constraint is based upon the map width."),e=this.getValueCheckingRange(b,"YTile",10,0,this.mapHeight-1,"This constraint is based upon the map height."),g=this.getValueCheckingRange(b,"XTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),f=this.getValueCheckingRange(b,"YTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),h=this.getValueCheckingRange(b,"Angle",-1,0,359,"");-1==h?
(c.useExistingAngle=!0,h=45):c.useExistingAngle=!1;c.xPos=parseInt(d,10)*MazeGlobals.TILE_SIZE+parseInt(g,10);c.yPos=parseInt(e,10)*MazeGlobals.TILE_SIZE+parseInt(f,10);c.angle=Trig.degreesToMazeAngleUnits(parseInt(h,10));c.landscapeFile=this.iniObj[b].Landscape;null==c.landscapeFile&&(c.landscapeFile="");c.usingALandscape=0<c.landscapeFile.length;c.useExistingLandscape=!c.usingALandscape;c.usingALandscape&&(c.landscapeOffsetFromTop=this.iniObj[b].LandscapeOffsetFromTop,null==c.landscapeOffsetFromTop&&
(c.landscapeOffsetFromTop=0),c.landscapeOffsetFromTop=parseInt(c.landscapeOffsetFromTop,10),d=this.iniObj[b].LandscapeStartAngle,null==d&&(d=0),c.landscapeStartAngle=Trig.degreesToMazeAngleUnits(parseInt(d,10)));c.backgroundFile=this.iniObj[b].BackGround;if(null==c.backgroundFile||0>=c.backgroundFile.length)c.backgroundFile=this.iniObj[b].Background;if(null==c.backgroundFile||0>=c.backgroundFile.length)c.backgroundFile="";c.backgroundFromFile=0<c.backgroundFile.length;c.backgroundFromRGB=!c.backgroundFromFile;
if(c.backgroundFromRGB){var d=this.getValueCheckingRange(b,"SkyRed",-11,0,255,""),e=this.getValueCheckingRange(b,"SkyGreen",-11,0,255,""),g=this.getValueCheckingRange(b,"SkyBlue",-11,0,255,""),f=this.getValueCheckingRange(b,"GroundRed",-11,0,255,""),h=this.getValueCheckingRange(b,"GroundGreen",-11,0,255,""),k=this.getValueCheckingRange(b,"GroundBlue",-11,0,255,""),l=this.getValueCheckingRange(b,"SkyRedStep",-11,-10,10,""),m=this.getValueCheckingRange(b,"SkyGreenStep",-11,-10,10,""),n=this.getValueCheckingRange(b,
"SkyBlueStep",-11,-10,10,""),p=this.getValueCheckingRange(b,"GroundRedStep",-11,-10,10,""),q=this.getValueCheckingRange(b,"GroundGreenStep",-11,-10,10,"");b=this.getValueCheckingRange(b,"GroundBlueStep",-11,-10,10,"");d=parseInt(d,10);e=parseInt(e,10);g=parseInt(g,10);f=parseInt(f,10);h=parseInt(h,10);k=parseInt(k,10);l=parseInt(l,10);m=parseInt(m,10);n=parseInt(n,10);p=parseInt(p,10);q=parseInt(q,10);b=parseInt(b,10);if(-11==d||-11==e||-11==g||-11==f||-11==h||-11==k||-11==l||-11==m||-11==n||-11==
p||-11==q||-11==b)c.useExistingBackground=!0,console.log("MazeConfig.js: In dest: "+a+" no background file specified and missing background RGB values.");c.skyRed=-11==d?40:d;c.skyGreen=-11==e?125:e;c.skyBlue=-11==g?225:g;c.groundRed=-11==f?100:f;c.groundGreen=-11==h?80:h;c.groundBlue=-11==k?40:k;c.skyRedStep=-11==l?2:l;c.skyGreenStep=-11==m?0:m;c.skyBlueStep=-11==n?0:n;c.groundRedStep=-11==p?1:p;c.groundGreenStep=-11==q?1:q;c.groundBlueStep=-11==b?1:b}c.backgroundFromFile&&(c.useExistingBackground=
!1);0==a&&(console.log("MazeConfig: [Dest0] | fXPos: "+c.xPos),console.log("MazeConfig: [Dest0] | fYPos:"+c.yPos),console.log("MazeConfig: [Dest0] | fAngle:"+c.angle),c.useExistingBackground&&this.textAreaBox.dumpError("[MazeConfig: [Dest0] in MazeConfig.ini requires either a 'Background' value or all Red, Green, Blue background values must be specified."));return c};
MazeConfig.prototype.getValueCheckingRange=function(a,c,b,d,e,g){var f=this.iniObj[a][c];null==f&&(f=b);if(f>e||f<d){if(f===b)return f;this.textAreaBox.dumpError(c+" in "+a+" of MazeConfig.ini must be in the range "+d+" to "+e+". "+g+" Using default values.");f=b}return f};if(null==TextAreaBox||"object"!=typeof TextAreaBox)var TextAreaBox={};TextAreaBox=function(a,c,b,d,e,g){this.context=a;this.backGroundClrStr=c;this.origTextClrStr=this.textClrStr=b;this.leftStartPoint=d;this.width=e;this.height=g;this.displayText="";this.clear()};TextAreaBox.prototype.TOP_MARGIN=12;TextAreaBox.prototype.MARGIN=5;TextAreaBox.prototype.LINE_HEIGHT=12;TextAreaBox.prototype.LINE_SEPARATOR_HEIGHT=2;TextAreaBox.prototype.FONT_STYLE="11px Arial,sans-serif";
TextAreaBox.prototype.ERROR_TEXT_COLOR="red";TextAreaBox.prototype.clear=function(){this.context.beginPath();this.context.rect(this.leftStartPoint,0,this.width,this.height);this.context.closePath();this.context.fillStyle=this.backGroundClrStr;this.context.fill();this.context.stroke()};TextAreaBox.prototype.setTextClr=function(a){this.textClrStr=a};
TextAreaBox.prototype.setDisplayText=function(a){this.displayText=a.replace(/(\r)/gm,"");this.context.font=this.FONT_STYLE;this.context.fillStyle=this.textClrStr;this.displayText=this.wrapLines(this.displayText,this.width-this.leftStartPoint)};
TextAreaBox.prototype.render=function(){this.context.font=this.FONT_STYLE;this.context.fillStyle=this.textClrStr;var a=this.displayText.split(/\r\n|\r|\n/),c=this.TOP_MARGIN,b=this;a.forEach(function(a){b.context.fillText(a,b.leftStartPoint+b.MARGIN,c);c=c+b.LINE_HEIGHT+b.LINE_SEPARATOR_HEIGHT})};TextAreaBox.prototype.dumpText=function(a){this.clear();this.setTextClr(this.origTextClrStr);this.setDisplayText(a);this.render()};
TextAreaBox.prototype.dumpError=function(a){this.clear();this.setTextClr(this.ERROR_TEXT_COLOR);this.setDisplayText(a);console.log(a);this.render()};TextAreaBox.prototype.wrapLines=function(a,c){var b=this,d="";a.split(/\r\n|\r|\n/).forEach(function(a){var c="",f="";a.split(" ").forEach(function(a){b.context.measureText(""+c+f+a).width<b.width-(b.MARGIN+b.MARGIN)?c=""+c+f+a:(d=""+d+c+"\n",c=a);f=" "});d=""+d+c+"\n"});return d};if(null==MathUtils||"object"!=typeof MathUtils)var MathUtils={};MathUtils.base10ToBase36=function(a){var c="";return c=9<a?String.fromCharCode(97+(a-10)):parseInt(a,10)};MathUtils.base36ToBase10=function(a){var c=0;a=a.charCodeAt(0);48<=a&&57>=a&&(c=a-48);57<a&&(c=a-97+10);return c};
MathUtils.logarithmBaseTwo=function(a){switch(a){case 2:return 1;case 4:return 2;case 8:return 3;case 16:return 4;case 32:return 5;case 64:return 6;case 128:return 7;case 256:return 8;case 512:return 9;case 1024:return 10;default:return 6}};if(null==ImageCanvas||"object"!=typeof ImageCanvas)var ImageCanvas={};ImageCanvas=function(a,c,b,d,e){this.fileDictatesSize=!1;3==arguments.length&&(this.fileDictatesSize=!0);this.document=a;this.mazeId=c;this.fileName=b;this.width=d;this.height=e;this.fileHeight=this.fileWidth=0;this.imageData=this.image=this.context=this.canvas=null};
ImageCanvas.prototype.loadFile=function(a){var c="undefined"!=typeof a;this.canvas=document.createElement("canvas");if(this.canvas.getContext&&(this.context=this.canvas.getContext("2d"),this.context.getImageData)){this.image=new Image;this.image.style.position="absolute";this.image.style.left="-1000px";this.document.body.appendChild(this.image);var b=this;this.image.onload=function(){console.log("ImageCanvas.js - Load Image: "+MazeGlobals.MAZE_DIR+"/"+b.mazeId+"/"+b.fileName);b.fileWidth=this.width;
b.fileHeight=this.height;b.fileDictatesSize&&(b.width=b.fileWidth,b.height=b.fileHeight);b.canvas.width=b.width;b.canvas.height=b.height;b.canvas.style.width=b.width+"px";b.canvas.style.height=b.height+"px";b.context.drawImage(b.image,0,0,b.width,b.height);try{try{b.imageData=b.context.getImageData(0,0,b.width,b.height)}catch(d){netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead"),b.imageData=b.context.getImageData(0,0,b.width,b.height)}}catch(e){c&&a(!1,"Unable to access image data: "+
MazeGlobals.MAZE_DIR+"/"+b.mazeId+"/"+b.fileName+" error:"+e.message)}c&&a(!0)};this.image.onerror=function(){c&&a(!1,"File not found: "+MazeGlobals.MAZE_DIR+"/"+b.mazeId+"/"+b.fileName)};this.image.src=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.fileName}};
ImageCanvas.prototype.showAlphaData=function(){for(var a=[],c=0,b=this.imageData.data.length;c<b;c+=4){var d=Math.floor(c/4/this.width),e=c/4-d*this.width;a[d]||(a[d]=[]);a[d][e]=0==this.imageData.data[c+3]?0:1}alert("ImageCanvas Alpha:\r\n"+a)};if(null==IniFile||"object"!=typeof IniFile)var IniFile={};IniFile=function(a,c){this.iniObj=null;this.mazeId=a;this.fileName=c};
IniFile.prototype.loadFile=function(a){var c="undefined"!=typeof a,b=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.fileName;console.log("IniFile.js - Load file: "+d);var e=this;b.onreadystatechange=function(){4<=b.readyState&&(200==b.status&&(e.iniObj=IniFile.parseIniString(b.responseText),c&&a(!0)),404==b.status&&c&&a(!1,"File not found: "+MazeGlobals.MAZE_DIR+"/"+e.mazeId+"/"+e.fileName))};b.open("GET",d);b.send(null)};
IniFile.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};
IniFile.parseIniString=function(a){var c=/^\s*\[\s*([^\]]*)\s*\]\s*$/,b=/^\s*([\w\.\-\_]+)\s*=\s*(.*?)\s*$/,d=/^\s*;.*$/,e={},g=null;a.split(/\r\n|\r|\n/).forEach(function(a){a=a.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,"");d.test(a)||(b.test(a)?(a=a.match(b),g?e[g][a[1]]=a[2]:e[a[1]]=a[2]):c.test(a)?(a=a.match(c),e[a[1]]={},g=a[1]):0==a.length&&g&&(g=null))});return e};function KeyboardController(a,c){var b={};document.onkeydown=function(d){d=(d||window.event).keyCode;if(!(d in a))return!0;d in b||(b[d]=null,a[d](),0!==c&&(b[d]=setInterval(a[d],c)));return!1};document.onkeyup=function(a){a=(a||window.event).keyCode;a in b&&(null!==b[a]&&clearInterval(b[a]),delete b[a])};window.onblur=function(){for(key in b)null!==b[key]&&clearInterval(b[key]);b={}}};if(null==MapData||"object"!=typeof MapData)var MapData={};MapData=function(a,c,b){this.document=a;this.mazeId=c;this.textAreaBox=b;this.mapWidth=8;this.mapWidthShift=3;this.mapHeight=8;this.numWallImgs=0;this.wallCanvasImgs={};this.mapData="1111111110000001100000011000011110001101100000011000000111111111".split("")};MapData.prototype.MAP_DATA_FILE="WallData.txt";MapData.prototype.mapWidth=8;MapData.prototype.mapWidthShift=3;MapData.prototype.mapHeight=8;MapData.prototype.numWallImgs=0;
MapData.prototype.loadDataFile=function(a){var c="undefined"!=typeof a,b=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.MAP_DATA_FILE,e=this;b.onreadystatechange=function(){4<=b.readyState&&(200==b.status&&(MapData.parseMapData(e,b.responseText),c&&a(!0)),404==b.status&&c&&a(!1,"File not found: "+e.MAP_DATA_FILE))};b.open("GET",d);b.send(null)};
MapData.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};MapData.prototype.isWall=function(a){return"0"!=this.mapData[a]};MapData.prototype.getValue=function(a){return 0>a||a>=this.mapHeight<<this.mapWidthShift?"0":this.mapData[a]};MapData.prototype.convertPointToMapPos=function(a,c){return(c<<this.mapWidthShift)+a};
MapData.prototype.loadAssociatedImages=function(a){var c="undefined"!=typeof a,b=1,d=this,e=function(){var g=MathUtils.base10ToBase36(b),f=new ImageCanvas(d.document,d.mazeId,"Wall"+g+".gif",64,64);f.loadFile(function(h,k){!1===h&&console.log(k);d.wallCanvasImgs[g]=f;b++;b>d.numWallImgs?c&&a(!0):e()})};e()};MapData.prototype.getCanvasImage=function(a){return this.wallCanvasImgs.hasOwnProperty(a)?this.wallCanvasImgs[a]:null};
MapData.parseMapData=function(a,c){var b=0;a.mapWidth=-1;for(var d="",e=c.split(/\r\n|\r|\n/),g=0;g<e.length;g++){var f=e[g];if(null!=f&&0!=f.length&&(f=f.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,""),0!=f.length)){b++;if(-1==a.mapWidth)if(a.mapWidth=f.length,MapData.isLineLengthGood(a.mapWidth))a.mapWidthShift=MathUtils.logarithmBaseTwo(a.mapWidth);else{a.mapWidth=-1;break}else if(f.length!=a.mapWidth){e="Line # "+b+" in file '"+a.MAP_DATA_FILE+"' is inconsistent with the first line of the file. ";
e+="Each line in the file must be the exact same length.";a.textAreaBox.dumpError(e);break}f=f.toLowerCase();d+=f}}console.log("num lines in map file is: "+b);-1!=a.mapWidth&&(a.mapHeight=b,a.mapData=d.split(""),MapData.setAllTimeHighImageNum(a))};MapData.setAllTimeHighImageNum=function(a){for(var c=0;c<a.mapData.length;c++){var b=MathUtils.base36ToBase10(a.mapData[c]);a.numWallImgs=Math.max(b,a.numWallImgs)}console.log("MapData.js: number of wall images expected is: "+a.numWallImgs)};
MapData.isLineLengthGood=function(a){return 16!=a&&32!=a&&64!=a&&128!=a&&256!=a?(a="The length of the first line in file '"+that.MAP_DATA_FILE+"' is "+a+".",that.textAreaBox.dumpError(a+"Line length must be 16, 32, 64, 128, or 256."),!1):!0};if(null==PropData||"object"!=typeof PropData)var PropData={};PropData=function(a,c,b,d,e,g){this.document=a;this.mazeId=c;this.textAreaBox=b;this.mapWidth=e;this.mapWidthShift=g;this.mapHeight=d;this.numPropImgs=0;this.propCanvasImgs={};this.propData="0000000000000000000003000000201000000000000000000000000000000000".split("")};PropData.prototype.PROP_DATA_FILE="PropData.txt";PropData.prototype.mapWidth=8;PropData.prototype.mapHeight=8;PropData.prototype.mapWidthShift=3;
PropData.prototype.numPropImgs=0;PropData.prototype.loadDataFile=function(a){var c="undefined"!=typeof a,b=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.PROP_DATA_FILE,e=this;b.onreadystatechange=function(){4<=b.readyState&&(200==b.status&&(PropData.parsePropData(e,b.responseText),c&&a(!0)),404==b.status&&c&&a(!1,"File not found: "+e.PROP_DATA_FILE))};b.open("GET",d);b.send(null)};
PropData.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};PropData.prototype.isProp=function(a){return"0"!=this.propData[a]};PropData.prototype.getValue=function(a){return 0>a||a>=this.mapHeight<<this.mapWidthShift?"0":this.propData[a]};PropData.prototype.convertPointToMapPos=function(a,c){return(c<<this.mapWidthShift)+a};
PropData.prototype.loadAssociatedImages=function(a){var c="undefined"!=typeof a,b=1,d=this,e=function(){var g=MathUtils.base10ToBase36(b),f=new ImageCanvas(d.document,d.mazeId,"Prop"+g+".gif",64,64);f.loadFile(function(h,k){!1===h&&console.log(k);d.propCanvasImgs[g]=f;b++;b>d.numPropImgs?c&&a(!0):e()})};e()};PropData.prototype.getCanvasImage=function(a){return this.propCanvasImgs.hasOwnProperty(a)?this.propCanvasImgs[a]:null};
PropData.parsePropData=function(a,c){var b=0;a.mapWidth=-1;for(var d="",e=c.split(/\r\n|\r|\n/),g=0;g<e.length;g++){var f=e[g];if(null!=f&&0!=f.length&&(f=f.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,""),0!=f.length)){b++;if(-1==a.mapWidth)if(a.mapWidth=f.length,PropData.isLineLengthGood(a.mapWidth))a.mapWidthShift=MathUtils.logarithmBaseTwo(a.mapWidth);else{a.mapWidth=-1;break}else if(f.length!=a.mapWidth){e="Line # "+b+" in file '"+a.PROP_DATA_FILE+"' is inconsistent with the first line of the file. ";
e+="Each line in the file must be the exact same length.";a.textAreaBox.dumpError(e);break}f=f.toLowerCase();d+=f}}console.log("num lines in map file is: "+b);b!=a.mapHeight&&(e="The number of lines in the file '"+a.PROP_DATA_FILE+"' doesn't match the ",a.textAreaBox.dumpError(e+"number of lines in the wall file ."));-1!=a.mapWidth&&(a.mapHeight=b,a.propData=d.split(""),PropData.setAllTimeHighImageNum(a))};
PropData.setAllTimeHighImageNum=function(a){for(var c=0;c<a.propData.length;c++){var b=MathUtils.base36ToBase10(a.propData[c]);a.numPropImgs=Math.max(b,a.numPropImgs)}console.log("PropData.js: number of prop images expected is: "+a.numPropImgs)};PropData.isLineLengthGood=function(a){return 16!=a&&32!=a&&64!=a&&128!=a&&256!=a?(a="The length of the first line in file '"+that.PROP_DATA_FILE+"' is "+a+".",that.textAreaBox.dumpError(a+"Line length must be 16, 32, 64, 128, or 256."),!1):!0};if(null==Maze||"object"!=typeof Maze)var Maze={};
Maze=function(a,c,b,d,e,g,f,h,k){this.canvasContext=a;this.textAreaBox=c;this.mapData=b;this.propData=d;this.mazeConfig=e;this.questions=g;this.questionPosData=f;this.background=h;this.landscape=k;this.trig=new Trig;this.curDest=this.mazeConfig.advanceToDest(0);this.playerX=this.curDest.xPos;this.playerY=this.curDest.yPos;this.playerArc=this.curDest.angle;this.background.setBackgroundFromDest(this.mazeConfig.document,this.mazeConfig.mazeId,this.curDest);this.landscape.setLandscapeFromDest(this.mazeConfig.document,
this.mazeConfig.mazeId,this.curDest);this.overlay=new Overlay(a);this.memPixels=this.canvasContext.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT);this.setPlayerPos()};Maze.prototype.WALL_HEIGHT=64;Maze.prototype.trig=null;Maze.prototype.curDest=null;Maze.prototype.playerX=130;Maze.prototype.playerY=130;Maze.prototype.playerArc=0;Maze.prototype.playerDistanceToTheProjectionPlane=277;Maze.prototype.playerHeight=32;Maze.prototype.playerSpeed=16;
Maze.prototype.projectionPlaneYCenter=MazeGlobals.PROJECTIONPLANEHEIGHT/2;Maze.prototype.propHitItems=[];Maze.prototype.clipper=[];Maze.prototype.playerXDir=0;Maze.prototype.playerYDir=0;Maze.prototype.curTrap=null;Maze.prototype.SLICE_WIDTH=1;Maze.prototype.mapData=null;Maze.prototype.propData=null;Maze.prototype.questions=null;Maze.prototype.questionPosData=null;Maze.prototype.mazeConfig=null;Maze.prototype.canvasContext=null;Maze.prototype.textAreaBox=null;Maze.prototype.memPixels=null;
Maze.prototype.background=null;Maze.prototype.overlay=null;Maze.prototype.landscape=null;Maze.prototype.curQuestion="0";Maze.prototype.setPixel=function(a,c,b,d,e){null!=this.memPixels&&(a=4*(a+c*this.memPixels.width),this.memPixels.data[a+0]=b,this.memPixels.data[a+1]=d,this.memPixels.data[a+2]=e,this.memPixels.data[a+3]=255)};
Maze.prototype.castRayForHorizHit=function(a){var c,b,d=0,e=0;c=WallHitItemConsts.BOTTOM_SIDE_HIT;a>this.trig.ANGLE0&&a<this.trig.ANGLE180?(d=(this.playerY>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT)+MazeGlobals.TILE_SIZE,e=this.playerX+(d-this.playerY)*this.trig.iTanTable[a],b=MazeGlobals.TILE_SIZE):(c=WallHitItemConsts.TOP_SIDE_HIT,d=this.playerY>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT,e=this.playerX+(d-this.playerY)*this.trig.iTanTable[a],b=-MazeGlobals.TILE_SIZE,
d--);d=new WallHitItem(WallHitItemConsts.HORIZ_HIT,d,e,a);d.hitSide=c;if(a==this.trig.ANGLE0||a==this.trig.ANGLE180)d.distToItem=Number.MAX_VALUE;else for(c=this.trig.xStepTable[a];;){var e="0",g=d.calcAndSetMapPos(this.mapData);d.calcAndSetOffTheMap(this.mapData);if(d.offTheMap)break;else if(this.propData.isProp(g)&&"undefined"==typeof this.propHitItems.findFirst(function(a){return a.mapPos==g}))e=new PropHitItem(g,this.trig),e.setPropHitItemData(this.mapData,this.playerX,this.playerY,this.playerArc),
this.propHitItems.push(e);else if("0"!=(e=this.questionPosData.getQuestionItemTypeAtSpecial(g,this.questions,this.curQuestion))&&"undefined"==typeof this.propHitItems.findFirst(function(a){return a.mapPos==g}))e=new QuestionHitItem(g,this.trig,e),e.setPropHitItemData(this.mapData,this.playerX,this.playerY,this.playerArc),this.propHitItems.push(e);else if(!this.propData.isProp(g)&&this.mapData.isWall(d.mapPos)){d.distToItem=(d.intersection-this.playerX)*this.trig.iCosTable[a];break}else d.intersection+=
c,d.gridLine+=b}return d};
Maze.prototype.castRayForVertHit=function(a){var c,b,d=0,e=0;c=WallHitItemConsts.RIGHT_SIDE_HIT;a<this.trig.ANGLE90||a>this.trig.ANGLE270?(d=(this.playerX>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT)+MazeGlobals.TILE_SIZE,e=this.playerY+(d-this.playerX)*this.trig.tanTable[a],b=MazeGlobals.TILE_SIZE):(c=WallHitItemConsts.LEFT_SIDE_HIT,d=this.playerX>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT,e=this.playerY+(d-this.playerX)*this.trig.tanTable[a],b=-MazeGlobals.TILE_SIZE,
d--);d=new WallHitItem(WallHitItemConsts.VERT_HIT,d,e,a);d.hitSide=c;if(a==this.trig.ANGLE90||a==this.trig.ANGLE270)d.distToItem=Number.MAX_VALUE;else for(c=this.trig.yStepTable[a];;){var e="0",g=d.calcAndSetMapPos(this.mapData);d.calcAndSetOffTheMap(this.mapData);if(d.offTheMap)break;else if(this.propData.isProp(g)&&"undefined"==typeof this.propHitItems.findFirst(function(a){return a.mapPos==g}))e=new PropHitItem(g,this.trig),e.setPropHitItemData(this.mapData,this.playerX,this.playerY,this.playerArc),
this.propHitItems.push(e);else if("0"!=(e=this.questionPosData.getQuestionItemTypeAtSpecial(g,this.questions,this.curQuestion))&&"undefined"==typeof this.propHitItems.findFirst(function(a){return a.mapPos==g}))e=new QuestionHitItem(g,this.trig,e),e.setPropHitItemData(this.mapData,this.playerX,this.playerY,this.playerArc),this.propHitItems.push(e);else if(!this.propData.isProp(g)&&this.mapData.isWall(d.mapPos)){d.distToItem=(d.intersection-this.playerY)*this.trig.iSinTable[a];break}else d.intersection+=
c,d.gridLine+=b}return d};
Maze.prototype.castProp=function(a){var c=a.dist,b=a.colMidProp;if(-1!=c&&-1!=b){var d=~~(MazeGlobals.PROP_HEIGHT*MazeGlobals.PLAYER_DIST_TO_PROJ_PLANE/c),e=MazeGlobals.PROJECTIONPLANEHEIGHT-(this.projectionPlaneYCenter+~~(0.5*d)),g=this.questionPosData.getCanvasImage("?");if(a instanceof QuestionHitItem)a=a.questionItemType,"0"!=a&&(g=this.questionPosData.getCanvasImage(a));else{a=this.propData.propData[a.mapPos];if("0"==a)return;g=this.propData.getCanvasImage(a);if(null==g)return}a=b-(d>>1);for(var f=
b+(d>>1),h=b;0<=h&&h<MazeGlobals.PROJECTIONPLANEWIDTH&&h>=a;h--)if(c<this.clipper[h]){var k=~~((h-a<<MazeGlobals.TILE_SIZE_SHIFT)/d);this.drawVertSliceOfImage(h,e,d,g.imageData,MazeGlobals.TILE_SIZE,k)}for(h=b+1;0<=h&&h<MazeGlobals.PROJECTIONPLANEWIDTH&&h<f;h++)c<this.clipper[h]&&(k=~~((h-a<<MazeGlobals.TILE_SIZE_SHIFT)/d),this.drawVertSliceOfImage(h,e,d,g.imageData,MazeGlobals.TILE_SIZE,k))}};
Maze.prototype.drawLandscape=function(a,c){if(this.curDest.usingALandscape){var b=this.curDest.landscapeOffsetFromTop,d=this.curDest.landscapeStartAngle,e=this.landscape.width,g=this.landscape.height,f=this.landscape.memPixels;if(a>=d&&a<d+e)for(var h=0;h<g;h++){var k=4*~~(e*h+(a-d)),l=f.data[k+0],m=f.data[k+1],n=f.data[k+2];0!=f.data[k+3]&&this.setPixel(c,b+h,l,m,n)}}};
Maze.prototype.renderOneFrame=function(){this.background.copyBackgroundTo(this.memPixels);var a=this.playerArc-this.trig.ANGLE30;0>a&&(a=this.trig.ANGLE360+a);this.clipper=[];for(var c=this.clipper.length=0;c<MazeGlobals.PROJECTIONPLANEWIDTH;c++)this.clipper[c]=Number.MAX_VALUE;this.propHitItems=[];for(c=this.propHitItems.length=0;c<MazeGlobals.PROJECTIONPLANEWIDTH;c+=this.SLICE_WIDTH){var b=this.castRayForHorizHit(a),d=this.castRayForVertHit(a);d.offTheMap&&b.offTheMap||(b=determineClosestHit(b,
d),-0>=b.distToItem&&(b.distToItem=1),this.drawLandscape(a,c),this.drawWallSlice(c,b));a+=this.SLICE_WIDTH;a>=this.trig.ANGLE360&&(a-=this.trig.ANGLE360);d=b=null}this.propHitItems.sort(function(a,b){return b.dist-a.dist});for(a=0;a<this.propHitItems.length;a++)this.castProp(this.propHitItems[a]);null!=this.curTrap&&this.curTrap.usingOverlay&&this.overlay.copyOverlayTo(this.memPixels);this.paint()};
Maze.prototype.drawWallSlice=function(a,c){var b,d,e;if(!c.offTheMap){b=~~c.intersection%MazeGlobals.TILE_SIZE;d=c.distToItem;d/=this.trig.fishTable[a];var g=this.playerDistanceToTheProjectionPlane/d*this.WALL_HEIGHT;e=this.projectionPlaneYCenter+~~(0.5*g);e=MazeGlobals.PROJECTIONPLANEHEIGHT-e;var f=this.SLICE_WIDTH,h=0;c.hitSide==WallHitItemConsts.TOP_SIDE_HIT||c.hitSide==WallHitItemConsts.RIGHT_SIDE_HIT?h=0<b-f?b-f:0:(h=b+f<=MazeGlobals.TILE_SIZE?b+f:MazeGlobals.TILE_SIZE,h=MazeGlobals.TILE_SIZE-
h);b=this.mapData.mapData[c.mapPos];"0"!=b&&(b=this.mapData.getCanvasImage(b),null!=b&&(this.drawVertSliceOfImage(a,e,g,b.imageData,MazeGlobals.TILE_SIZE,h),this.propData.isProp(c.mapPos)||(this.clipper[a]=d)))}};
Maze.prototype.drawVertSliceOfImage=function(a,c,b,d,e,g){var f=e/b,h=0;b=c+b;for(var k=e*e;c<b;c++){h++;var l=c*MazeGlobals.PROJECTIONPLANEWIDTH+a;0<=l&&l<MazeGlobals.PROJECTIONPLANE_WIDTHTIMESHEIGHT&&(l=~~(f*h)*e+g,0<=l&&l<k&&(l*=4,0!=d.data[l+3]&&this.setPixel(a,c,d.data[l],d.data[l+1],d.data[l+2])))}};Maze.prototype.paint=function(){this.canvasContext.putImageData(this.memPixels,0,0)};
Maze.prototype.rotateLeft=function(){(this.playerArc-=this.trig.ANGLE10)<this.trig.ANGLE0&&(this.playerArc+=this.trig.ANGLE360);this.setPlayerPos()};Maze.prototype.rotateRight=function(){(this.playerArc+=this.trig.ANGLE10)>=this.trig.ANGLE360&&(this.playerArc-=this.trig.ANGLE360);this.setPlayerPos()};Maze.prototype.setPlayerPos=function(){this.playerXDir=this.trig.cosTable[this.playerArc];this.playerYDir=this.trig.sinTable[this.playerArc]};
Maze.prototype.moveForward=function(){this.attemptMove(this.playerX+this.playerXDir*this.playerSpeed,this.playerY+this.playerYDir*this.playerSpeed)};Maze.prototype.moveBackward=function(){this.attemptMove(this.playerX-this.playerXDir*this.playerSpeed,this.playerY-this.playerYDir*this.playerSpeed)};
Maze.prototype.hyperspaceToQuestion=function(a){var c=this.questionPosData.getPositionFromQuestionNum(a);null!=c&&(a=c>>this.mapData.mapWidthShift,c%=this.mapData.mapWidth,this.playerArc>=this.trig.ANGLE315&&this.playerArc<=this.trig.ANGLE360?c-=1.5:this.playerArc>=this.trig.ANGLE0&&this.playerArc<=this.trig.ANGLE45?c-=1.5:this.playerArc>this.trig.ANGLE45&&this.playerArc<=this.trig.ANGLE135?a-=1.5:this.playerArc>this.trig.ANGLE135&&this.playerArc<=this.trig.ANGLE225?c+=1.5:this.playerArc>this.trig.ANGLE225&&
this.playerArc<=this.trig.ANGLE315&&(a+=1.5),this.playerX=(c+1)*MazeGlobals.TILE_SIZE,this.playerY=(a+1)*MazeGlobals.TILE_SIZE)};
Maze.prototype.checkTraps=function(a,c){var b=this.curTrap;this.curTrap=this.mazeConfig.insideATrap(a,c);if(null==this.curTrap)return!1;if(this.curTrap==b)return!0;this.curTrap.usingOverlay&&this.overlay.setOverlayFromTrap(this.mazeConfig.document,this.mazeConfig.mazeId,this.curTrap);if(this.curTrap.usingDest){b=this.mazeConfig.advanceToDest(this.curTrap.gotoDest);if(null==b)return!0;this.curDest=b;b.useExistingBackground||this.background.setBackgroundFromDest(this.mazeConfig.document,this.mazeConfig.mazeId,
this.curDest);b.useExistingLandscape||this.landscape.setLandscapeFromDest(this.mazeConfig.document,this.mazeConfig.mazeId,this.curDest);this.playerX=this.curDest.xPos;this.playerY=this.curDest.yPos;this.curDest.useExistingAngle||(this.playerArc=this.curDest.angle,this.playerXDir=this.trig.cosTable[fPlayerArc],this.playerYDir=this.trig.sinTable[fPlayerArc])}return!0};
Maze.prototype.checkQuestions=function(a){var c=this.questionPosData.getQuestionItemTypeAt(a,this.questions,this.curQuestion);"?"==c?(a=this.questionPosData.getValue(a),this.curQuestion!=a&&(this.curQuestion=a,a=this.questions.returnQuestion(this.curQuestion),this.textAreaBox.dumpText(a.getQuestionAnswerText()))):"0"==this.curQuestion||"A"!=c&&"B"!=c&&"C"!=c&&"D"!=c||(this.curQuestion="0",this.textAreaBox.dumpText(""))};
Maze.prototype.attemptMove=function(a,c){var b=a>>MazeGlobals.TILE_SIZE_SHIFT,d=c>>MazeGlobals.TILE_SIZE_SHIFT,b=this.mapData.convertPointToMapPos(b,d);b<this.mapData.mapHeight<<this.mapData.mapWidthShift&&!this.mapData.isWall(b)?(this.playerX=a,this.playerY=c,this.checkQuestions(b),this.checkTraps(this.playerX,this.playerY)):(b=a>>MazeGlobals.TILE_SIZE_SHIFT,d=this.playerY>>MazeGlobals.TILE_SIZE_SHIFT,b=this.mapData.convertPointToMapPos(b,d),b<this.mapData.mapHeight<<this.mapData.mapWidthShift&&
!this.mapData.isWall(b)?(this.playerX=a,this.checkQuestions(b),this.checkTraps(this.playerX,this.playerY)):(b=this.playerX>>MazeGlobals.TILE_SIZE_SHIFT,d=c>>MazeGlobals.TILE_SIZE_SHIFT,b=this.mapData.convertPointToMapPos(b,d),b<this.mapData.getMapHeight<<this.mapData.mapWidthShift&&!this.mapData.isWall(b)&&(this.playerY=c,this.checkQuestions(b),this.checkTraps(this.playerX,this.playerY))))};if(null==Overlay||"object"!=typeof Overlay)var Overlay={};Overlay=function(a){this.memPixels=a.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT)};Overlay.prototype.overlayFile="";Overlay.prototype.usingOverlay=!1;Overlay.prototype.memPixels=[];Overlay.prototype.setOverlayFromTrap=function(a,c,b){b.usingOverlay&&(this.document=a,this.mazeId=c,this.usingOverlay=b.usingOverlay,this.overlayFile=b.overlayFile,this.usingOverlay&&this.createOverlayFromFile())};
Overlay.prototype.createOverlayFromFile=function(){var a=new ImageCanvas(this.document,this.mazeId,this.overlayFile,MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT),c=this;a.loadFile(function(b,d){if(!0===b)for(var e=0;e<MazeGlobals.PROJECTIONPLANEHEIGHT;e++)for(var g=0;g<MazeGlobals.PROJECTIONPLANEWIDTH;g++){var f=4*(g+e*MazeGlobals.PROJECTIONPLANEWIDTH);c.setPixel(g,e,a.imageData.data[f+0],a.imageData.data[f+1],a.imageData.data[f+2],a.imageData.data[f+3])}else console.log(d)})};
Overlay.prototype.copyOverlayTo=function(a){for(var c=0;c<MazeGlobals.PROJECTIONPLANEHEIGHT;c++)for(var b=0;b<MazeGlobals.PROJECTIONPLANEWIDTH;b++){var d=4*(b+c*this.memPixels.width);0!=this.memPixels.data[d+3]&&(a.data[d+0]=this.memPixels.data[d+0],a.data[d+1]=this.memPixels.data[d+1],a.data[d+2]=this.memPixels.data[d+2],a.data[d+3]=this.memPixels.data[d+3])}};
Overlay.prototype.setPixel=function(a,c,b,d,e,g){a=4*(a+c*this.memPixels.width);this.memPixels.data[a+0]=b;this.memPixels.data[a+1]=d;this.memPixels.data[a+2]=e;this.memPixels.data[a+3]=g};if(null==Landscape||"object"!=typeof Landscape)var Landscape={};Landscape=function(a){this.canvasContext=a};Landscape.prototype.landscapeFile="";Landscape.prototype.usingALandscape=!1;Landscape.prototype.canvasContext=null;Landscape.prototype.width=0;Landscape.prototype.height=0;Landscape.prototype.memPixels=[];
Landscape.prototype.setLandscapeFromDest=function(a,c,b,d){b.usingALandscape&&(this.document=a,this.mazeId=c,this.usingALandscape=b.usingALandscape,this.landscapeFile=b.landscapeFile,this.landscapeOffsetFromTop=b.landscapeOffsetFromTop,this.landscapeStartAngle=b.landscapeStartAngle,this.createLandscapeFromFile(d))};
Landscape.prototype.createLandscapeFromFile=function(a){var c="undefined"!==typeof a,b=new ImageCanvas(this.document,this.mazeId,this.landscapeFile),d=this;b.loadFile(function(e,g){if(!0===e){d.width=b.width;d.height=b.height;d.memPixels=d.canvasContext.createImageData(d.width,d.height);for(var f=0;f<d.height;f++)for(var h=0;h<d.width;h++){var k=4*(h+f*d.width);d.setPixel(h,f,b.imageData.data[k+0],b.imageData.data[k+1],b.imageData.data[k+2],b.imageData.data[k+3])}c&&a(!0)}else console.log(g),c&&a(!1)})};
Landscape.prototype.copyLandscapeTo=function(a){for(var c=0;c<this.memPixels.height;c++)for(var b=0;b<this.memPixels.width;b++){var d=4*(b+c*this.memPixels.width),e=4*(b+c*MazeGlobals.PROJECTIONPLANEWIDTH);e+4<a.data.length&&(a.data[e+0]=this.memPixels.data[d+0],a.data[e+1]=this.memPixels.data[d+1],a.data[e+2]=this.memPixels.data[d+2],a.data[e+3]=this.memPixels.data[d+3])}};
Landscape.prototype.setPixel=function(a,c,b,d,e,g){a=4*(a+c*this.memPixels.width);this.memPixels.data[a+0]=b;this.memPixels.data[a+1]=d;this.memPixels.data[a+2]=e;this.memPixels.data[a+3]=g};if(null==Background||"object"!=typeof Background)var Background={};Background=function(a){this.memPixels=a.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT)};Background.prototype.backgroundFile="";Background.prototype.backgroundFromFile=!1;Background.prototype.backgroundFromRGB=!0;Background.prototype.memPixels=[];Background.prototype.skyRed=40;Background.prototype.skyGreen=125;Background.prototype.skyBlue=225;Background.prototype.skyRedStep=2;
Background.prototype.skyGreenStep=0;Background.prototype.skyBlueStep=0;Background.prototype.groundRed=100;Background.prototype.groundGreen=80;Background.prototype.groundBlue=40;Background.prototype.groundRedStep=1;Background.prototype.groundGreenStep=1;Background.prototype.groundBlueStep=1;
Background.prototype.setBackgroundFromDest=function(a,c,b,d){b.useExistingBackground&&console.log("Background.js: programmer error... check useExistingBackground property before calling createBackgroundFromDest(). ");this.document=a;this.mazeId=c;this.backgroundFile=b.backgroundFile;this.backgroundFromFile=b.backgroundFromFile;this.backgroundFromRGB=b.backgroundFromRGB;this.skyRed=b.skyRed;this.skyGreen=b.skyGreen;this.skyBlue=b.skyBlue;this.groundRed=b.groundRed;this.groundGreen=b.groundGreen;this.groundBlue=
b.groundBlue;this.skyRedStep=b.skyRedStep;this.skyGreenStep=b.skyGreenStep;this.skyBlueStep=b.skyBlueStep;this.groundRedStep=b.groundRedStep;this.groundGreenStep=b.groundGreenStep;this.groundBlueStep=b.groundBlueStep;this.backgroundFromRGB&&this.createGradientBackground(d);this.backgroundFromFile&&this.createBackgroundFromFile(d)};
Background.prototype.createBackgroundFromFile=function(a){var c="undefined"!==typeof a,b=new ImageCanvas(this.document,this.mazeId,this.backgroundFile,MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT),d=this;b.loadFile(function(e,g){if(!0===e){for(var f=0;f<MazeGlobals.PROJECTIONPLANEHEIGHT;f++)for(var h=0;h<MazeGlobals.PROJECTIONPLANEWIDTH;h++){var k=4*(h+f*MazeGlobals.PROJECTIONPLANEWIDTH);d.setPixel(h,f,b.imageData.data[k+0],b.imageData.data[k+1],b.imageData.data[k+2])}c&&a(!0)}else console.log(g),
c&&a(!1)})};
Background.prototype.createGradientBackground=function(a){for(var c="undefined"!==typeof a,b=this.skyRed,d=this.skyGreen,e=this.skyBlue,g=MazeGlobals.PROJECTIONPLANEHEIGHT>>1,f=0;f<g;f++){for(var h=0;h<MazeGlobals.PROJECTIONPLANEWIDTH;h++)this.setPixel(h,f,b,d,e);b+=this.skyRedStep;b=255<b?255:b;b=0>b?0:b;d+=this.skyGreenStep;d=255<d?255:d;d=0>d?0:d;e+=this.skyBlueStep;e=255<e?255:e;e=0>e?0:e}b=this.groundRed;d=this.groundGreen;e=this.groundBlue;for(f=g;f<MazeGlobals.PROJECTIONPLANEHEIGHT;f++){for(h=0;h<
MazeGlobals.PROJECTIONPLANEWIDTH;h++)this.setPixel(h,f,b,d,e);b+=this.groundRedStep;b=255<b?255:b;b=0>b?0:b;d+=this.groundGreenStep;d=255<d?255:d;d=0>d?0:d;e+=this.groundBlueStep;e=255<e?255:e;e=0>e?0:e}c&&a(!0)};
Background.prototype.copyBackgroundTo=function(a){for(var c=0;c<MazeGlobals.PROJECTIONPLANEHEIGHT;c++)for(var b=0;b<MazeGlobals.PROJECTIONPLANEWIDTH;b++){var d=4*(b+c*this.memPixels.width);a.data[d+0]=this.memPixels.data[d+0];a.data[d+1]=this.memPixels.data[d+1];a.data[d+2]=this.memPixels.data[d+2];a.data[d+3]=this.memPixels.data[d+3]}};
Background.prototype.setPixel=function(a,c,b,d,e){a=4*(a+c*this.memPixels.width);this.memPixels.data[a+0]=b;this.memPixels.data[a+1]=d;this.memPixels.data[a+2]=e;this.memPixels.data[a+3]=255};var WallHitItemConsts=function(){return{TOP_SIDE_HIT:0,RIGHT_SIDE_HIT:1,BOTTOM_SIDE_HIT:2,LEFT_SIDE_HIT:3,HORIZ_HIT:0,VERT_HIT:1}}();if(null==WallHitItem||"object"!=typeof WallHitItem)var WallHitItem={};WallHitItem=function(a,c,b,d){this.hitType=a;this.gridLine=c;this.intersection=b;this.castArc=d};WallHitItem.prototype.gridLine=0;WallHitItem.prototype.intersection=0;WallHitItem.prototype.hitType=WallHitItemConsts.HORIZ_HIT;WallHitItem.prototype.hitSide=WallHitItemConsts.TOP_SIDE_HIT;
WallHitItem.prototype.offTheMap=!1;WallHitItem.prototype.distToItem=0;WallHitItem.prototype.xGridIndex=0;WallHitItem.prototype.yGridIndex=0;WallHitItem.prototype.mapPos=0;WallHitItem.prototype.castArc=0;WallHitItem.prototype.isHorizHit=function(){return this.hitType==WallHitItemConsts.HORIZ_HIT};WallHitItem.prototype.isVertHit=function(){return this.hitType==WallHitItemConsts.VERT_HIT};
function determineClosestHit(a,c){return c.offTheMap&&a.offTheMap||c.offTheMap?a:a.offTheMap?c:a.distToItem<c.distToItem?a:c}
WallHitItem.prototype.calcAndSetMapPos=function(a){this.hitType==WallHitItemConsts.HORIZ_HIT?(this.xGridIndex=~~(this.intersection/MazeGlobals.TILE_SIZE),this.yGridIndex=this.gridLine>>MazeGlobals.TILE_SIZE_SHIFT):(this.xGridIndex=this.gridLine>>MazeGlobals.TILE_SIZE_SHIFT,this.yGridIndex=~~(this.intersection/MazeGlobals.TILE_SIZE));return this.mapPos=a.convertPointToMapPos(this.xGridIndex,this.yGridIndex)};
WallHitItem.prototype.calcAndSetOffTheMap=function(a){if(this.xGridIndex>=a.mapWidth||this.yGridIndex>=a.mapHeight||0>this.xGridIndex||0>this.yGridIndex)this.distToItem=Number.MAX_VALUE,this.offTheMap=!0;return this.offTheMap};if(null==PropHitItem||"object"!=typeof PropHitItem)var PropHitItem={};PropHitItem=function(a,c){this.mapPos=a;this.colMidProp=this.dist=-1;this.trig=c};PropHitItem.prototype.mapPos=0;PropHitItem.prototype.dist=-1;PropHitItem.prototype.colMidProp=-1;PropHitItem.prototype.trig;
PropHitItem.prototype.setPropHitItemData=function(a,c,b,d){var e=(~~this.mapPos%a.mapWidth<<MazeGlobals.TILE_SIZE_SHIFT)+(MazeGlobals.TILE_SIZE>>1),g=(this.mapPos>>a.mapWidthShift<<MazeGlobals.TILE_SIZE_SHIFT)+(MazeGlobals.TILE_SIZE>>1);a=0;var f=c-e,h=b-g;a=0==h?Math.abs(f):~~Math.sqrt(Math.abs(f*f+h*h));var k=0;if(b==g&&0>c-e)k=0;else if(c==e&&0>b-g)k=90;else if(b==g&&0<c-e)k=180;else if(c==e&&0<b-g)k=270;else{k=0;if(c<e&&b<g)k=0;else if(c>e&&b<g)k=180;else if(c>e&&b>g)k=180;else if(c<e&&b>g)k=
360;else return;c=Math.atan(h/f);k=Trig.radToDegrees(c)+k}c=~~(k*this.trig.ANGLE60/60);d>this.trig.ANGLE270&&c<this.trig.ANGLE90&&(d-=this.trig.ANGLE360);c>this.trig.ANGLE270&&d<this.trig.ANGLE90&&(c-=this.trig.ANGLE360);d=~~((MazeGlobals.PROJECTIONPLANEWIDTH>>1)-(d-c));this.dist=a=0<=d&&d<MazeGlobals.PROJECTIONPLANEWIDTH?a/this.trig.fishTable[d]:a/(1/Math.cos(this.trig.arcToRad(k)));this.colMidProp=d};if(null==Questions||"object"!=typeof Questions)var Questions={};Questions=function(a,c,b){this.document=a;this.mazeId=c;this.textAreaBox=b;this.numQuestions=0;this.questions=[];this.iniObj={}};Questions.prototype.QUESTIONS_INI_FILE="Questions.ini";
Questions.prototype.loadQuestionsFile=function(a){var c="undefined"!=typeof a,b=new IniFile(this.mazeId,this.QUESTIONS_INI_FILE),d=this;b.loadFile(function(e,g){if(e){console.log("MazeConfig.js: MazeConfig.ini successfully loaded.");d.iniObj=b.iniObj;var f=d.iniObj.General.Ver;f!=GeneralConfig.MAUTH_VER_NUM&&console.log("Questions.js: Questions.ini file may be out of date. Expected version: "+GeneralConfig.MAUTH_VER_NUM+"Version found: "+f);d.numQuestions=d.iniObj.General.NumQuestions;for(f=0;f<d.numQuestions;f++){var h=
d.readQuestion(f);d.questions.push(h)}c&&a(!0)}else d.textAreaBox.dumpError("error: "+g),c&&a(!1,g)})};
Questions.prototype.readQuestion=function(a){var c=new Question,b="Question"+a;c.questionNum=a;c.totalQuestions=this.numQuestions;c.id=this.iniObj[b].ID;c.question=this.iniObj[b].Question;c.answerA=this.iniObj[b].AnswerA;c.answerB=this.iniObj[b].AnswerB;c.answerC=this.iniObj[b].AnswerC;c.answerD=this.iniObj[b].AnswerD;c.xRelAnswerA=parseInt(this.iniObj[b].XRelAnswerA,10);c.yRelAnswerA=parseInt(this.iniObj[b].YRelAnswerA,10);c.xRelAnswerB=parseInt(this.iniObj[b].XRelAnswerB,10);c.yRelAnswerB=parseInt(this.iniObj[b].YRelAnswerB,
10);c.xRelAnswerC=parseInt(this.iniObj[b].XRelAnswerC,10);c.yRelAnswerC=parseInt(this.iniObj[b].YRelAnswerC,10);c.xRelAnswerD=parseInt(this.iniObj[b].XRelAnswerD,10);c.yRelAnswerD=parseInt(this.iniObj[b].YRelAnswerD,10);return c};Questions.prototype.returnQuestion=function(a){for(var c=0;c<this.numQuestions;c++){var b=this.questions[c];if(b.id==a)return b}console.log("Questions.js: unable to find question "+num);return this.questions[0]};if(null==Question||"object"!=typeof Question)var Question={};Question=function(){this.questionNum=0;this.totalQuestions="0";this.yRelAnswerD=this.xRelAnswerD=this.yRelAnswerC=this.xRelAnswerC=this.yRelAnswerB=this.xRelAnswerB=this.yRelAnswerA=this.xRelAnswerA=this.answerD=this.answerC=this.answerB=this.answerA=this.question=this.id=""};Question.prototype.getQuestionAnswerText=function(){return this.question+"\n\nA. "+this.answerA+"\nB. "+this.answerB+"\nC. "+this.answerC+"\nD. "+this.answerD+"\n\n(Follow the path in the maze associated with the correct answer.)"};if(null==QuestionPosData||"object"!=typeof QuestionPosData)var QuestionPosData={};QuestionPosData=function(a,c,b,d,e,g){this.document=a;this.mazeId=c;this.textAreaBox=b;this.mapWidth=e;this.mapWidthShift=g;this.mapHeight=d;this.questionToPosMap={};this.questionCanvasImgs={};this.questionPosData="0000000000000000001000000000000000000000000200000000003000000000".split("")};QuestionPosData.prototype.QUESTION_POS_DATA_FILE="QuestionPosData.txt";QuestionPosData.prototype.mapWidth=8;
QuestionPosData.prototype.mapHeight=8;QuestionPosData.prototype.mapWidthShift=3;
QuestionPosData.prototype.loadDataFile=function(a){var c="undefined"!=typeof a,b=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.QUESTION_POS_DATA_FILE,e=this;b.onreadystatechange=function(){4<=b.readyState&&(200==b.status&&(QuestionPosData.parseQuestionPosData(e,b.responseText),c&&a(!0,"success loading question pos data")),404==b.status&&c&&a(!1,"File not found: "+e.QUESTION_POS_DATA_FILE))};b.open("GET",d);b.send(null)};
QuestionPosData.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};QuestionPosData.prototype.isQuestionPosItem=function(a){return"0"!=this.questionPosData[a]};QuestionPosData.prototype.getValue=function(a){return 0>a||a>=this.mapHeight<<this.mapWidthShift?"0":this.questionPosData[a]};
QuestionPosData.prototype.setupPositionList=function(){for(var a=0;a<this.questionPosData.length;a++)"0"!=this.questionPosData[a]&&(this.questionToPosMap[this.questionPosData[a]]=a)};QuestionPosData.prototype.convertPointToMapPos=function(a,c){return(c<<this.mapWidthShift)+a};
QuestionPosData.prototype.getQuestionItemTypeAt=function(a,c,b){if("0"!=this.getValue(a))return"?";if("0"==b)return"0";var d=this.questionToPosMap[b],e=d>>this.mapWidthShift,d=d%this.mapWidth,g=c.returnQuestion(b);c=e+g.yRelAnswerA;b=e+g.yRelAnswerB;var f=e+g.yRelAnswerC,e=e+g.yRelAnswerD,h=d+g.xRelAnswerA,k=d+g.xRelAnswerB,l=d+g.xRelAnswerC,d=d+g.xRelAnswerD;return h>this.mapWidth||k>this.mapWidth||l>this.mapWidth||d>this.mapWidth||c>this.mapHeight||b>this.mapHeight||f>this.mapHeight||e>this.mapHeight?
"0":(c<<this.mapWidthShift)+h==a?"A":(b<<this.mapWidthShift)+k==a?"B":(f<<this.mapWidthShift)+l==a?"C":(e<<this.mapWidthShift)+d==a?"D":"0"};QuestionPosData.prototype.getQuestionItemTypeAtSpecial=function(a,c,b){c=this.getQuestionItemTypeAt(a,c,b);return"?"!=c?c:this.getValue(a)==b?"0":"?"};
QuestionPosData.prototype.loadAssociatedImages=function(a){var c="undefined"!=typeof a,b=[],d=[];b[0]="?";d["?"]="QuestionMark.gif";b[1]="A";d.A="AnswerA.gif";b[2]="B";d.B="AnswerB.gif";b[3]="C";d.C="AnswerC.gif";b[4]="D";d.D="AnswerD.gif";var e=0,g=this,f=function(){var h=b[e],k=new ImageCanvas(g.document,g.mazeId,d[h],64,64);k.loadFile(function(d,m){!1===d&&console.log(m);g.questionCanvasImgs[h]=k;e++;e>=b.length?c&&a(!0):f()})};f()};
QuestionPosData.prototype.getCanvasImage=function(a){return this.questionCanvasImgs.hasOwnProperty(a)?this.questionCanvasImgs[a]:null};QuestionPosData.prototype.getPositionFromQuestionNum=function(a){return this.questionToPosMap[a]};
QuestionPosData.parseQuestionPosData=function(a,c){var b=0;a.mapWidth=-1;for(var d="",e=c.split(/\r\n|\r|\n/),g=0;g<e.length;g++){var f=e[g];if(null!=f&&0!=f.length&&(f=f.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,""),0!=f.length)){b++;if(-1==a.mapWidth)if(a.mapWidth=f.length,QuestionPosData.isLineLengthGood(a.mapWidth))a.mapWidthShift=MathUtils.logarithmBaseTwo(a.mapWidth);else{a.mapWidth=-1;break}else if(f.length!=a.mapWidth){e="Line # "+b+" in file '"+a.QUESTION_POS_DATA_FILE+"' is inconsistent with the first line of the file. ";
e+="Each line in the file must be the exact same length.";a.textAreaBox.dumpError(e);break}f=f.toLowerCase();d+=f}}console.log("num lines in map file is: "+b);b!=a.mapHeight&&(e="The number of lines in the file '"+a.QUESTION_POS_DATA_FILE+"' doesn't match the ",a.textAreaBox.dumpError(e+"number of lines in the wall file ."));-1!=a.mapWidth&&(a.mapHeight=b,a.questionPosData=d.split(""),a.setupPositionList())};
QuestionPosData.isLineLengthGood=function(a){return 16!=a&&32!=a&&64!=a&&128!=a&&256!=a?(a="The length of the first line in file '"+that.QUESTION_POS_DATA_FILE+"' is "+a+".",that.textAreaBox.dumpError(a+"Line length must be 16, 32, 64, 128, or 256."),!1):!0};if(null==QuestionHitItem||"object"!=typeof QuestionHitItem)var QuestionHitItem={};QuestionHitItem=function(a,c,b){PropHitItem.apply(this,arguments);this.questionItemType=b};QuestionHitItem.prototype=new PropHitItem;QuestionHitItem.prototype.constructor=QuestionHitItem;QuestionHitItem.prototype.questionItemType="0";if(null==MazeLoader||"object"!=typeof MazeLoader)var MazeLoader={};MazeLoader.maze=null;MazeLoader.mazeId=null;MazeLoader.mapData=null;MazeLoader.propData=null;MazeLoader.mazeConfig=null;MazeLoader.textAreaBox=null;MazeLoader.questions=null;MazeLoader.questionPosData=null;MazeLoader.openingCredits=null;MazeLoader.background=null;MazeLoader.landscape=null;MazeLoader.ctx=null;
var captureKey=!1,openingCreditsDelayCompleteCallBack=function(){console.log("MazeLoader.js: Opening credits complete.");MazeLoader.maze=new Maze(MazeLoader.ctx,MazeLoader.textAreaBox,MazeLoader.mapData,MazeLoader.propData,MazeLoader.mazeConfig,MazeLoader.questions,MazeLoader.questionPosData,MazeLoader.background,MazeLoader.landscape);MazeLoader.maze.renderOneFrame()},questionPosDataLoadAssociatedImagesCallBack=function(a,c){a?(console.log("MazeLoader.js: successfully loaded Questions pos data images "),
setTimeout(openingCreditsDelayCompleteCallBack,MazeLoader.openingCredits.getStopWatchTimeRemaining())):MazeLoader.textAreaBox.dumpError("MazeLoader.js: successfully loaded Questions pos data images: "+c)},loadQuestionsCallBack=function(a,c){a?(console.log("MazeLoader.js: successfully loaded Questions file"),MazeLoader.questionPosData=new QuestionPosData(document,MazeLoader.mazeId,MazeLoader.textAreaBox,MazeLoader.mapData.mapHeight,MazeLoader.mapData.mapWidth,MazeLoader.mapData.mapWidthShift),MazeLoader.questionPosData.loadDataFile(function(a,
c){console.log("MazeLoader.js: question pos file load status:"+a+" "+c);MazeLoader.questionPosData.loadAssociatedImages(questionPosDataLoadAssociatedImagesCallBack)})):MazeLoader.textAreaBox.dumpError("error unable to load Questions file: "+c)},loadLandscapeCallBack=function(a){a?(console.log("MazeLoader.js: successfully primed the landscape"),MazeLoader.questions=new Questions(document,MazeLoader.mazeId,MazeLoader.textAreaBox),MazeLoader.questions.loadQuestionsFile(loadQuestionsCallBack)):MazeLoader.textAreaBox.dumpError("error priming the landscape: "+
message)},loadBackgroundCallBack=function(a){a?(console.log("MazeLoader.js: successfully primed the background"),a=MazeLoader.mazeConfig.advanceToDest(0),MazeLoader.landscape=new Landscape(MazeLoader.ctx),MazeLoader.landscape.setLandscapeFromDest(MazeLoader.mazeConfig.document,MazeLoader.mazeConfig.mazeId,a,loadLandscapeCallBack)):MazeLoader.textAreaBox.dumpError("error priming the background: "+message)},propDataLoadAssociatedImagesCallBack=function(a,c){if(a){console.log("MazeLoader.js: successfully loaded associated prop image files");
var b=MazeLoader.mazeConfig.advanceToDest(0);MazeLoader.background=new Background(MazeLoader.ctx);MazeLoader.background.setBackgroundFromDest(MazeLoader.mazeConfig.document,MazeLoader.mazeConfig.mazeId,b,loadBackgroundCallBack)}else MazeLoader.textAreaBox.dumpError("error unable to load associated images: "+c)},loadDataFileCallBack=function(a,c){a?(console.log("MazeLoader.js: Prop Data file successfully loaded."),MazeLoader.propData.loadAssociatedImages(propDataLoadAssociatedImagesCallBack)):MazeLoader.textAreaBox.dumpError("error unable to load Prop Data file: "+
c)},MazeLoader=function(a){MazeLoader.mazeId=a};MazeLoader.prototype.createCanvas=function(){var a=document.getElementById("targetCanvasDiv"),c=document.createElement("canvas");c.setAttribute("width",640);c.setAttribute("height",200);a.appendChild(c);"undefined"!=typeof G_vmlCanvasManager&&(c=G_vmlCanvasManager.initElement(c));return c};
MazeLoader.prototype.loadAndStart=function(){MazeLoader.mapData=new MapData(document,MazeLoader.mazeId,MazeLoader.textAreaBox);MazeLoader.mapData.loadDataFile(function(a,c){a?(console.log("MazeLoader.js: Map Data file successfully loaded."),MazeLoader.mapData.loadAssociatedImages(function(a,c){a?(console.log("MazeLoader.js: successfully loaded associated wall image files"),MazeLoader.mazeConfig=new MazeConfig(document,MazeLoader.mazeId,MazeLoader.textAreaBox,MazeLoader.mapData.mapHeight,MazeLoader.mapData.mapWidth),
MazeLoader.mazeConfig.loadConfigFile(function(){MazeLoader.propData=new PropData(document,MazeLoader.mazeId,MazeLoader.textAreaBox,MazeLoader.mapData.mapHeight,MazeLoader.mapData.mapWidth,MazeLoader.mapData.mapWidthShift);MazeLoader.propData.loadDataFile(loadDataFileCallBack)})):MazeLoader.textAreaBox.dumpError("error unable to load associated images: "+c)})):MazeLoader.textAreaBox.dumpError("error unable to load Map Data file: "+c)})};
MazeLoader.prototype.init=function(){var a=this.createCanvas();MazeLoader.ctx=a.getContext("2d");MazeLoader.textAreaBox=new TextAreaBox(MazeLoader.ctx,"black","#aaaaaa",MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.TEXTBOXWIDTH,MazeGlobals.TEXTBOXHEIGHT);MazeLoader.textAreaBox.dumpText("Welcome to the EdVenture Maze emulator! Use this emulator\nto test out your maze before publishing and pushing it out to\nmobile devices.\n\nUse the arrow keys on your computer keyboard to navigate.\n\nLook for question marks (?) giving you clues as to which \npathway (A, B, C, or D) is best. Good luck!");
if(null==MazeLoader.ctx.createImageData)MazeLoader.textAreaBox.dumpError("Please upgrade your browser. Sorry, your browser is out of date for this viewer to function properly.");else{var c=this,b=new GeneralConfig(document,MazeLoader.mazeId,MazeLoader.textAreaBox);b.loadConfigFile(function(a,d){a?(console.log("MazeLoader.js: General Config successfully loaded."),b.loadAssociatedImages(function(a,e){a?(console.log("MazeLoader.html: successfully loaded associated general config images."),MazeLoader.openingCredits=
new OpeningCredits(b),MazeLoader.openingCredits.drawOpeningCredits(MazeLoader.ctx),MazeLoader.openingCredits.startTheStopWatch(),c.loadAndStart()):MazeLoader.textAreaBox.dumpError("error unable to load General Config associated images: "+d)})):MazeLoader.textAreaBox.dumpError("error unable to load General Config file: "+d)});var d=function(a){captureKey&&(MazeLoader.maze.hyperspaceToQuestion(a),MazeLoader.maze.renderOneFrame());captureKey=!1};KeyboardController({37:function(){MazeLoader.maze.rotateLeft();
MazeLoader.maze.renderOneFrame()},38:function(){MazeLoader.maze.moveForward();MazeLoader.maze.renderOneFrame()},39:function(){MazeLoader.maze.rotateRight();MazeLoader.maze.renderOneFrame()},40:function(){MazeLoader.maze.moveBackward();MazeLoader.maze.renderOneFrame()},191:function(){captureKey=!0;setTimeout(function(){captureKey=!1},1500)},49:function(){d("1")},50:function(){d("2")},51:function(){d("3")},52:function(){d("4")},53:function(){d("5")},54:function(){d("6")},55:function(){d("7")},56:function(){d("8")},
57:function(){d("9")},65:function(){d("a")},66:function(){d("b")},67:function(){d("c")},68:function(){d("d")},69:function(){d("e")},70:function(){d("f")},71:function(){d("g")},72:function(){d("h")},73:function(){d("i")},74:function(){d("j")},75:function(){d("k")},76:function(){d("l")},77:function(){d("m")},78:function(){d("n")},79:function(){d("o")},80:function(){d("p")},81:function(){d("q")},82:function(){d("r")},83:function(){d("s")},84:function(){d("t")},85:function(){d("u")},86:function(){d("v")},
87:function(){d("w")},88:function(){d("x")},89:function(){d("y")},90:function(){d("z")}},100)}};
