var MazeGlobals=function(){return{PROJECTIONPLANEWIDTH:320,PROJECTIONPLANEHEIGHT:200,PROJECTIONPLANE_WIDTHTIMESHEIGHT:64E3,TEXTBOXWIDTH:320,TEXTBOXHEIGHT:200,TILE_SIZE:64,TILE_SIZE_SHIFT:6,MAZE_DIR:"MazeDir"}}();if(null==Background||"object"!=typeof Background)var Background={};Background=function(a){this.memPixels=a.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT);this.createGradientBackground()};Background.prototype.backgroundFile="";Background.prototype.isBackgroundFromFile=!1;Background.prototype.isBackgroundFromRGB=!0;Background.prototype.memPixels=[];Background.prototype.skyRed=40;Background.prototype.skyGreen=125;Background.prototype.skyBlue=225;
Background.prototype.skyRedStep=2;Background.prototype.skyGreenStep=0;Background.prototype.skyBlueStep=0;Background.prototype.groundRed=100;Background.prototype.groundGreen=80;Background.prototype.groundBlue=40;Background.prototype.groundRedStep=1;Background.prototype.groundGreenStep=1;Background.prototype.groundBlueStep=1;
Background.prototype.setBackgroundFromDest=function(a){a.useExistingBackground&&console.log("Background.js: programmer error... check useExistingBackground property before calling createBackgroundFromDest(). ");this.backgroundFile=a.backgroundFile;this.isBackgroundFromFile=a.isBackgroundFromFile;this.isBackgroundFromRGB=a.isBackgroundFromRGB;this.skyRed=a.skyRed;this.skyGreen=a.skyGreen;this.skyBlue=a.skyBlue;this.groundRed=a.groundRed;this.groundGreen=a.groundGreen;this.groundBlue=a.groundBlue;this.skyRedStep=
a.skyRedStep;this.skyGreenStep=a.skyGreenStep;this.skyBlueStep=a.skyBlueStep;this.groundRedStep=a.groundRedStep;this.groundGreenStep=a.groundGreenStep;this.groundBlueStep=a.groundBlueStep;this.backgroundFromRGB&&this.createGradientBackground()};
Background.prototype.createGradientBackground=function(){for(var a=this.skyRed,b=this.skyGreen,c=this.skyBlue,d=MazeGlobals.PROJECTIONPLANEHEIGHT>>1,e=0;e<d;e++){for(var g=0;g<MazeGlobals.PROJECTIONPLANEWIDTH;g++)this.setPixel(g,e,a,b,c);a+=this.skyRedStep;a=255<a?255:a;a=0>a?0:a;b+=this.skyGreenStep;b=255<b?255:b;b=0>b?0:b;c+=this.skyBlueStep;c=255<c?255:c;c=0>c?0:c}a=this.groundRed;b=this.groundGreen;c=this.groundBlue;for(e=d;e<MazeGlobals.PROJECTIONPLANEHEIGHT;e++){for(g=0;g<MazeGlobals.PROJECTIONPLANEWIDTH;g++)this.setPixel(g,
e,a,b,c);a+=this.groundRedStep;a=255<a?255:a;a=0>a?0:a;b+=this.groundGreenStep;b=255<b?255:b;b=0>b?0:b;c+=this.groundBlueStep;c=255<c?255:c;c=0>c?0:c}};Background.prototype.copyBackgroundTo=function(a){for(var b=0;b<MazeGlobals.PROJECTIONPLANEHEIGHT;b++)for(var c=0;c<MazeGlobals.PROJECTIONPLANEWIDTH;c++){var d=4*(c+b*this.memPixels.width);a.data[d+0]=this.memPixels.data[d+0];a.data[d+1]=this.memPixels.data[d+1];a.data[d+2]=this.memPixels.data[d+2];a.data[d+3]=this.memPixels.data[d+3]}};
Background.prototype.setPixel=function(a,b,c,d,e){a=4*(a+b*this.memPixels.width);this.memPixels.data[a+0]=c;this.memPixels.data[a+1]=d;this.memPixels.data[a+2]=e;this.memPixels.data[a+3]=255};if(null==Dest||"object"!=typeof Dest)var Dest={};
Dest=function(){this.angle=this.yPos=this.xPos=0;this.backgroundFromFile=this.useExistingAngle=!1;this.backgroundFromRGB=!0;this.useExistingBackground=!1;this.backgroundFile="";this.skyRed=40;this.skyGreen=125;this.skyBlue=225;this.skyRedStep=2;this.skyBlueStep=this.skyGreenStep=0;this.groundRed=100;this.groundGreen=80;this.groundBlue=40;this.groundBlueStep=this.groundGreenStep=this.groundRedStep=1;this.landscapeFile=this.useExistingLandscape=this.usingALandscape=!1;this.landscapeStartAngle=this.landscapeOffsetFromTop=
0};var GeneralConfig=function(){return{MAUTH_VER_NUM:"1.3",FULL_MAUTH_VER_NUM:"01.30"}}();if(null==ImageCanvas||"object"!=typeof ImageCanvas)var ImageCanvas={};ImageCanvas=function(a,b,c,d,e){this.document=a;this.mazeId=b;this.fileName=c;this.width=d;this.height=e;this.imageData=this.image=this.context=this.canvas=null};
ImageCanvas.prototype.loadFile=function(a){var b="undefined"!=typeof a;this.canvas=document.createElement("canvas");if(this.canvas.getContext&&(this.context=this.canvas.getContext("2d"),this.context.getImageData)){this.image=new Image;this.image.style.position="absolute";this.image.style.left="-1000px";this.document.body.appendChild(this.image);var c=this;this.image.onload=function(){c.canvas.width=c.width;c.canvas.height=c.height;c.canvas.style.width=c.width+"px";c.canvas.style.height=c.height+"px";
c.context.drawImage(c.image,0,0,c.width,c.height);try{try{c.imageData=c.context.getImageData(0,0,c.width,c.height)}catch(d){netscape.security.PrivilegeManager.enablePrivilege("UniversalBrowserRead"),c.imageData=c.context.getImageData(0,0,c.width,c.height)}}catch(e){b&&a(!1,"Unable to access image data: "+MazeGlobals.MAZE_DIR+"/"+c.mazeId+"/"+c.fileName+" error:"+e.message)}b&&a(!0)};this.image.onerror=function(){b&&a(!1,"File not found: "+MazeGlobals.MAZE_DIR+"/"+c.mazeId+"/"+c.fileName)};console.log("ImageCanvas.js - Load Image: "+
MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.fileName);this.image.src=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.fileName}};ImageCanvas.prototype.showAlphaData=function(){for(var a=[],b=0,c=this.imageData.data.length;b<c;b+=4){var d=Math.floor(b/4/this.width),e=b/4-d*this.width;a[d]||(a[d]=[]);a[d][e]=0==this.imageData.data[b+3]?0:1}alert("ImageCanvas Alpha:\r\n"+a)};if(null==IniFile||"object"!=typeof IniFile)var IniFile={};IniFile=function(a,b){this.iniObj=null;this.mazeId=a;this.fileName=b};
IniFile.prototype.loadFile=function(a){var b="undefined"!=typeof a,c=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.fileName;console.log("IniFile.js - Load file: "+d);var e=this;c.onreadystatechange=function(){4<=c.readyState&&(200==c.status&&(e.iniObj=IniFile.parseIniString(c.responseText),b&&a(!0)),404==c.status&&b&&a(!1,"File not found: "+MazeGlobals.MAZE_DIR+"/"+e.mazeId+"/"+e.fileName))};c.open("GET",d);c.send(null)};
IniFile.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};
IniFile.parseIniString=function(a){var b=/^\s*\[\s*([^\]]*)\s*\]\s*$/,c=/^\s*([\w\.\-\_]+)\s*=\s*(.*?)\s*$/,d=/^\s*;.*$/,e={},g=null;a.split(/\r\n|\r|\n/).forEach(function(a){a=a.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,"");d.test(a)||(c.test(a)?(a=a.match(c),g?e[g][a[1]]=a[2]:e[a[1]]=a[2]):b.test(a)?(a=a.match(b),e[a[1]]={},g=a[1]):0==a.length&&g&&(g=null))});return e};if(null==MapData||"object"!=typeof MapData)var MapData={};MapData=function(a,b,c){this.document=a;this.mazeId=b;this.textAreaBox=c;this.mapWidth=8;this.mapWidthShift=3;this.mapHeight=8;this.numWallImgs=0;this.wallCanvasImgs={};this.mapData="1111111110000001100000011000011110001101100000011000000111111111".split("")};MapData.prototype.MAP_DATA_FILE="WallData.txt";MapData.prototype.mapWidth=8;MapData.prototype.mapHeight=8;
MapData.prototype.loadDataFile=function(a){var b="undefined"!=typeof a,c=this.createXMLHttpRequest(),d=MazeGlobals.MAZE_DIR+"/"+this.mazeId+"/"+this.MAP_DATA_FILE,e=this;c.onreadystatechange=function(){4<=c.readyState&&(200==c.status&&(MapData.parseMapData(e,c.responseText),b&&a(!0)),404==c.status&&b&&a(!1,"File not found: "+e.MAP_DATA_FILE))};c.open("GET",d);c.send(null)};
MapData.prototype.createXMLHttpRequest=function(){var a=null;window.ActiveXObject?a=new ActiveXObject("Microsoft.XMLHTTP"):window.XMLHttpRequest&&(a=new XMLHttpRequest);return a};MapData.prototype.isWall=function(a){return"0"!=this.mapData[a]};MapData.prototype.getValue=function(a){return 0>a||a>=this.mapHeight<<this.mapWidthShift?"0":this.mapData[a]};MapData.prototype.convertPointToMapPos=function(a,b){return(b<<this.mapWidthShift)+a};
MapData.parseMapData=function(a,b){var c=0;a.mapWidth=-1;for(var d="",e=b.split(/\r\n|\r|\n/),g=0;g<e.length;g++){var f=e[g];if(null!=f&&0!=f.length&&(f=f.replace(/(\/\*([\s\S]*?)\*\/)|(\/\/(.*)$)/g,""),0!=f.length)){c++;if(-1==a.mapWidth)if(a.mapWidth=f.length,MapData.isLineLengthGood(a.mapWidth))a.mapWidthShift=MathUtils.logarithmBaseTwo(a.mapWidth);else{a.mapWidth=-1;break}else if(f.length!=a.mapWidth){e="Line # "+c+" in file '"+a.MAP_DATA_FILE+"' is inconsistent with the first line of the file. ";
e+="Each line in the file must be the exact same length.";a.textAreaBox.dumpError(e);break}f=f.toLowerCase();d+=f}}-1!=a.mapWidth&&(a.mapHeight=c,a.mapData=d.split(""),MapData.setAllTimeHighImageNum(a))};MapData.setAllTimeHighImageNum=function(a){for(var b=0;b<a.mapData.length;b++){var c=MathUtils.base36ToBase10(a.mapData[b]);a.numWallImgs=Math.max(c,a.numWallImgs)}console.log("MapData.js: number of wall images expected is: "+a.numWallImgs)};
MapData.isLineLengthGood=function(a){return 16!=a&&32!=a&&64!=a&&128!=a&&256!=a?(a="The length of the first line in file '"+that.MAP_DATA_FILE+"' is "+a+".",that.textAreaBox.dumpError(a+"Line length must be 16, 32, 64, 128, or 256."),!1):!0};
MapData.prototype.loadAssociatedImages=function(a){var b="undefined"!=typeof a,c=1,d=this,e=function(){var g=MathUtils.base10ToBase36(c),f=new ImageCanvas(d.document,d.mazeId,"Wall"+g+".gif",64,64);f.loadFile(function(k,l){!1===k&&console.log(l);d.wallCanvasImgs[g]=f;c++;c>d.numWallImgs?b&&a(!0):e()})};e()};MapData.prototype.getCanvasImage=function(a){return this.wallCanvasImgs.hasOwnProperty(a)?this.wallCanvasImgs[a]:null};if(null==MathUtils||"object"!=typeof MathUtils)var MathUtils={};MathUtils.base10ToBase36=function(a){var b="";return b=9<a?String.fromCharCode(97+(a-10)):parseInt(a,10)};MathUtils.base36ToBase10=function(a){var b=0;a=a.charCodeAt(0);48<=a&&57>=a&&(b=a-48);57<a&&(b=a-97+10);return b};
MathUtils.logarithmBaseTwo=function(a){switch(a){case 2:return 1;case 4:return 2;case 8:return 3;case 16:return 4;case 32:return 5;case 64:return 6;case 128:return 7;case 256:return 8;case 512:return 9;case 1024:return 10;default:return 6}};Maze=function(a,b,c){this.canvasContext=a;this.mapData=b;this.mazeConfig=c;this.trig=new Trig;this.curDest=this.mazeConfig.advanceToDest(0);this.playerX=this.curDest.xPos;this.playerY=this.curDest.yPos;this.playerArc=this.curDest.angle;this.background=new Background(a);this.background.setBackgroundFromDest(this.curDest);this.memPixels=this.canvasContext.createImageData(MazeGlobals.PROJECTIONPLANEWIDTH,MazeGlobals.PROJECTIONPLANEHEIGHT);this.setPlayerPos()};Maze.prototype.WALL_HEIGHT=64;
Maze.prototype.trig=null;Maze.prototype.curDest=null;Maze.prototype.playerX=130;Maze.prototype.playerY=130;Maze.prototype.playerArc=0;Maze.prototype.playerDistanceToTheProjectionPlane=277;Maze.prototype.playerHeight=32;Maze.prototype.playerSpeed=16;Maze.prototype.projectionPlaneYCenter=MazeGlobals.PROJECTIONPLANEHEIGHT/2;Maze.prototype.playerXDir=0;Maze.prototype.playerYDir=0;Maze.prototype.SLICE_WIDTH=1;Maze.prototype.mapData=null;Maze.prototype.mazeConfig=null;Maze.prototype.canvasContext=null;
Maze.prototype.memPixels=null;Maze.prototype.background=null;Maze.prototype.setPixel=function(a,b,c,d,e){null!=this.memPixels&&(a=4*(a+b*this.memPixels.width),this.memPixels.data[a+0]=c,this.memPixels.data[a+1]=d,this.memPixels.data[a+2]=e,this.memPixels.data[a+3]=255)};
Maze.prototype.castRayForHorizHit=function(a){var b,c,d=b=0;a>this.trig.ANGLE0&&a<this.trig.ANGLE180?(b=(this.playerY>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT)+MazeGlobals.TILE_SIZE,d=this.playerX+(b-this.playerY)*this.trig.iTanTable[a],c=MazeGlobals.TILE_SIZE):(b=this.playerY>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT,d=this.playerX+(b-this.playerY)*this.trig.iTanTable[a],c=-MazeGlobals.TILE_SIZE,b--);d=new WallHitItem(WallHitItem.prototype.HORIZ_HIT,b,d,a);if(a==
this.trig.ANGLE0||a==this.trig.ANGLE180)d.distToItem=Number.MAX_VALUE;else for(b=this.trig.xStepTable[a];d.calcAndSetMapPos(this.mapData),d.calcAndSetOffTheMap(this.mapData),!d.offTheMap;)if(this.mapData.isWall(d.mapPos)){d.distToItem=(d.intersection-this.playerX)*this.trig.iCosTable[a];break}else d.intersection+=b,d.gridLine+=c;return d};
Maze.prototype.castRayForVertHit=function(a){var b,c,d=b=0;a<this.trig.ANGLE90||a>this.trig.ANGLE270?(b=(this.playerX>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT)+MazeGlobals.TILE_SIZE,d=this.playerY+(b-this.playerX)*this.trig.tanTable[a],c=MazeGlobals.TILE_SIZE):(b=this.playerX>>MazeGlobals.TILE_SIZE_SHIFT<<MazeGlobals.TILE_SIZE_SHIFT,d=this.playerY+(b-this.playerX)*this.trig.tanTable[a],c=-MazeGlobals.TILE_SIZE,b--);d=new WallHitItem(WallHitItem.prototype.VERT_HIT,b,d,a);if(a==this.trig.ANGLE90||
a==this.trig.ANGLE270)d.distToItem=Number.MAX_VALUE;else for(b=this.trig.yStepTable[a];d.calcAndSetMapPos(this.mapData),d.calcAndSetOffTheMap(this.mapData),!d.offTheMap;)if(this.mapData.isWall(d.mapPos)){d.distToItem=(d.intersection-this.playerY)*this.trig.iSinTable[a];break}else d.intersection+=b,d.gridLine+=c;return d};
Maze.prototype.renderOneFrame=function(){this.background.copyBackgroundTo(this.memPixels);var a=this.playerArc-this.trig.ANGLE30;0>a&&(a=this.trig.ANGLE360+a);for(var b=0;b<MazeGlobals.PROJECTIONPLANEWIDTH;b+=this.SLICE_WIDTH){var c=this.castRayForHorizHit(a),d=this.castRayForVertHit(a);d.offTheMap&&c.offTheMap||(c=determineClosestHit(c,d),-0>=c.distToItem&&(c.distToItem=1),this.drawWallSlice(b,c));a+=this.SLICE_WIDTH;a>=this.trig.ANGLE360&&(a-=this.trig.ANGLE360)}this.paint()};
Maze.prototype.drawWallSlice=function(a,b){var c,d,e;if(!b.offTheMap){c=~~b.intersection%MazeGlobals.TILE_SIZE;d=b.distToItem;d/=this.trig.fishTable[a];d=this.WALL_HEIGHT*(this.playerDistanceToTheProjectionPlane/d);e=this.projectionPlaneYCenter+~~(0.5*d);e=MazeGlobals.PROJECTIONPLANEHEIGHT-e;var g=this.SLICE_WIDTH,f=0;b.hitSide==b.TOP_SIDE_HIT||b.getSide==b.RIGHT_SIDE_HIT?f=0<c-g?c-g:0:(f=c+g<=MazeGlobals.TILE_SIZE?c+g:MazeGlobals.TILE_SIZE,f=MazeGlobals.TILE_SIZE-f);c=this.mapData.mapData[b.mapPos];
"0"!=c&&(c=this.mapData.getCanvasImage(c),null!=c&&this.drawVertSliceOfImage(a,e,d,c.imageData,MazeGlobals.TILE_SIZE,f))}};Maze.prototype.drawVertSliceOfImage=function(a,b,c,d,e,g){var f=e/c,k=0;c=b+c;for(var l=e*e;b<c;b++){k++;var h=b*MazeGlobals.PROJECTIONPLANEWIDTH+a;0<=h&&h<MazeGlobals.PROJECTIONPLANE_WIDTHTIMESHEIGHT&&(h=~~(f*k)*e+g,0<=h&&h<l&&(h*=4,0!=d.data[h+3]&&this.setPixel(a,b,d.data[h],d.data[h+1],d.data[h+2])))}};
Maze.prototype.paint=function(){this.canvasContext.putImageData(this.memPixels,0,0)};Maze.prototype.rotateLeft=function(){(this.playerArc-=this.trig.ANGLE10)<this.trig.ANGLE0&&(this.playerArc+=this.trig.ANGLE360);this.setPlayerPos()};Maze.prototype.rotateRight=function(){(this.playerArc+=this.trig.ANGLE10)>=this.trig.ANGLE360&&(this.playerArc-=this.trig.ANGLE360);this.setPlayerPos()};Maze.prototype.setPlayerPos=function(){this.playerXDir=this.trig.cosTable[this.playerArc];this.playerYDir=this.trig.sinTable[this.playerArc]};
Maze.prototype.moveForward=function(){this.attemptMove(this.playerX+this.playerXDir*this.playerSpeed,this.playerY+this.playerYDir*this.playerSpeed)};Maze.prototype.moveBackward=function(){this.attemptMove(this.playerX-this.playerXDir*this.playerSpeed,this.playerY-this.playerYDir*this.playerSpeed)};
Maze.prototype.attemptMove=function(a,b){var c=a>>MazeGlobals.TILE_SIZE_SHIFT,d=b>>MazeGlobals.TILE_SIZE_SHIFT,c=this.mapData.convertPointToMapPos(c,d);c<this.mapData.mapHeight<<this.mapData.mapWidthShift&&!this.mapData.isWall(c)?(this.playerX=a,this.playerY=b):(c=a>>MazeGlobals.TILE_SIZE_SHIFT,d=this.playerY>>MazeGlobals.TILE_SIZE_SHIFT,c=this.mapData.convertPointToMapPos(c,d),c<this.mapData.mapHeight<<this.mapData.mapWidthShift&&!this.mapData.isWall(c)?this.playerX=a:(c=this.playerX>>MazeGlobals.TILE_SIZE_SHIFT,
d=b>>MazeGlobals.TILE_SIZE_SHIFT,c=this.mapData.convertPointToMapPos(c,d),c<this.mapData.getMapHeight<<this.mapData.mapWidthShift&&!this.mapData.isWall(c)&&(this.playerY=b)))};if(null==MazeConfig||"object"!=typeof MazeConfig)var MazeConfig={};MazeConfig=function(a,b,c,d,e){this.document=a;this.mazeId=b;this.textAreaBox=c;this.mapHeight=d;this.mapWidth=e;this.numTraps=0;this.numDests=1;this.traps=[];this.dests=[];this.iniObj={}};MazeConfig.prototype.MAZE_CONFIG_INI_FILE="MazeConfig.ini";
MazeConfig.prototype.loadConfigFile=function(a){var b="undefined"!=typeof a,c=new IniFile(this.mazeId,this.MAZE_CONFIG_INI_FILE),d=this;c.loadFile(function(e,g){if(e){console.log("MazeConfig.js: MazeConfig.ini successfully loaded.");d.iniObj={};d.iniObj.General={};d.iniObj.General.Ver="";d.iniObj.General.NumTraps=0;d.iniObj.General.NumTraps=0;d.iniObj.General.NumDests=0;d.iniObj=c.iniObj;var f=d.iniObj.General.Ver;f!=GeneralConfig.MAUTH_VER_NUM&&console.log("MazeConfig.js: MazeConfig.ini file may be out of date. Expected version: "+
GeneralConfig.MAUTH_VER_NUM+"Version found: "+f);d.numTraps=d.iniObj.General.NumTraps;d.numDests=d.iniObj.General.NumDests;0>=d.numTraps&&d.textAreaBox.dumpError("Number of destinations ('NumDests') in MazeConfig.ini file is zero.  You must have at least one for starting coordinates.");for(f=0;f<d.numDests;f++)d.dests.push(d.getDest(f,d.mapWidth,d.mapHeight));for(f=0;f<d.numTraps;f++)d.traps.push(d.getTrap(f,d.mapWidth,d.mapHeight,d.numDests));b&&a(!0)}else this.textAreaBox.dumpError("error: "+g),
b&&a(!1,g)})};MazeConfig.prototype.advanceToDest=function(a){return 0<=a&&a<this.numDests?this.dests[a]:null};
MazeConfig.prototype.getTrap=function(a,b,c,d){var e=new Trap;a="Trap"+a;var g=this.getValueCheckingRange(a,"LeftTile",15,0,this.mapWidth-1,"This constraint is based upon the map width.");b=this.getValueCheckingRange(a,"RightTile",16,0,b-1,"This constraint is based upon the map width.");var f=this.getValueCheckingRange(a,"TopTile",15,0,c-1,"This constraint is based upon the map height.");c=this.getValueCheckingRange(a,"BottomTile",16,0,c-1,"This constraint is based upon the map height.");var k=this.getValueCheckingRange(a,
"LeftTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),l=this.getValueCheckingRange(a,"RightTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),h=this.getValueCheckingRange(a,"TopTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),m=this.getValueCheckingRange(a,"BottomTileOffset",0,0,MazeGlobals.TILE_SIZE-1,"");e.leftSide=parseInt(g,10)*MazeGlobals.TILE_SIZE+parseInt(k,10);e.rightSide=parseInt(b,10)*MazeGlobals.TILE_SIZE+parseInt(l,10);e.topSide=parseInt(f,10)*MazeGlobals.TILE_SIZE+parseInt(h,10);e.bottomSide=parseInt(c,
10)*MazeGlobals.TILE_SIZE+parseInt(m,10);e.gotoDest=this.getValueCheckingRange(a,"GotoDest",-1,0,d-1,"");e.usingDest=-1!=e.gotoDest;e.usingSound=!1;e.soundFile=this.iniObj[a].SoundEffect;null===e.soundFile&&(e.soundFile="");e.overlayFile.usingOverlay=!1;e.overlayFile=this.iniObj[a].Overlay;null==e.overlayFile&&(e.overlayFile="");e.usingOverlay=0<e.overlayFile.length;return e};
MazeConfig.prototype.getDest=function(a,b,c){b=new Dest;c="Dest"+a;var d=this.getValueCheckingRange(c,"XTile",10,0,this.mapWidth-1,"This constraint is based upon the map width."),e=this.getValueCheckingRange(c,"YTile",10,0,this.mapHeight-1,"This constraint is based upon the map height."),g=this.getValueCheckingRange(c,"XTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),f=this.getValueCheckingRange(c,"YTileOffset",0,0,MazeGlobals.TILE_SIZE-1,""),k=this.getValueCheckingRange(c,"Angle",-1,0,359,"");-1==k?
(b.useExistingAngle=!0,k=45):b.useExistingAngle=!1;b.xPos=parseInt(d,10)*MazeGlobals.TILE_SIZE+parseInt(g,10);b.yPos=parseInt(e,10)*MazeGlobals.TILE_SIZE+parseInt(f,10);b.angle=Trig.degreesToMazeAngleUnits(parseInt(k,10));b.landscapeFile=this.iniObj[c].Landscape;null==b.landscapeFile&&(b.landscapeFile="");b.usingALandscape=0<b.landscapeFile.length;b.useExistingLandscape=!b.usingALandscape;b.usingALandscape&&(b.landscapeOffsetFromTop=this.iniObj[c].LandscapeOffsetFromTop,null==b.landscapeOffsetFromTop&&
(b.landscapeOffsetFromTop=0),b.landscapeOffsetFromTop=parseInt(b.landscapeOffsetFromTop,10),d=this.iniObj[c].LandscapeStartAngle,null==d&&(d=0),b.landscapeStartAngle=Trig.degreesToMazeAngleUnits(parseInt(d,10)));b.backgroundFile=this.iniObj[c].Background;if(null==b.backgroundFile||0>=b.backgroundFile.length)b.backgroundFile="";b.backgroundFromFile=0<b.backgroundFile.length;b.backgroundFromRGB=!b.backgroundFromFile;if(b.backgroundFromRGB){var d=this.getValueCheckingRange(c,"SkyRed",-11,0,255,""),e=
this.getValueCheckingRange(c,"SkyGreen",-11,0,255,""),g=this.getValueCheckingRange(c,"SkyBlue",-11,0,255,""),f=this.getValueCheckingRange(c,"GroundRed",-11,0,255,""),k=this.getValueCheckingRange(c,"GroundGreen",-11,0,255,""),l=this.getValueCheckingRange(c,"GroundBlue",-11,0,255,""),h=this.getValueCheckingRange(c,"SkyRedStep",-11,-10,10,""),m=this.getValueCheckingRange(c,"SkyGreenStep",-11,-10,10,""),n=this.getValueCheckingRange(c,"SkyBlueStep",-11,-10,10,""),p=this.getValueCheckingRange(c,"GroundRedStep",
-11,-10,10,""),q=this.getValueCheckingRange(c,"GroundGreenStep",-11,-10,10,"");c=this.getValueCheckingRange(c,"GroundBlueStep",-11,-10,10,"");d=parseInt(d,10);e=parseInt(e,10);g=parseInt(g,10);f=parseInt(f,10);k=parseInt(k,10);l=parseInt(l,10);h=parseInt(h,10);m=parseInt(m,10);n=parseInt(n,10);p=parseInt(p,10);q=parseInt(q,10);c=parseInt(c,10);if(-11==d||-11==e||-11==g||-11==f||-11==k||-11==l||-11==h||-11==m||-11==n||-11==p||-11==q||-11==c)b.useExistingBackground=!0,console.log("MazeConfig.js: In dest: "+
a+" no background file specified and missing background RGB values.");b.skyRed=-11==d?40:d;b.skyGreen=-11==e?125:e;b.skyBlue=-11==g?225:g;b.groundRed=-11==f?100:f;b.groundGreen=-11==k?80:k;b.groundBlue=-11==l?40:l;b.skyRedStep=-11==h?2:h;b.skyGreenStep=-11==m?0:m;b.skyBlueStep=-11==n?0:n;b.groundRedStep=-11==p?1:p;b.groundGreenStep=-11==q?1:q;b.groundBlueStep=-11==c?1:c}0==a&&(console.log("MazeConfig: [Dest0] | fXPos: "+b.xPos),console.log("MazeConfig: [Dest0] | fYPos:"+b.yPos),console.log("MazeConfig: [Dest0] | fAngle:"+
b.angle),b.useExistingBackground&&this.textAreaBox.dumpError("[MazeConfig: [Dest0] in MazeConfig.ini requires either a 'Background' value or all Red, Green, Blue background values must be specified."));return b};MazeConfig.prototype.getValueCheckingRange=function(a,b,c,d,e,g){var f=this.iniObj[a][b];null==f&&(f=c);if(f>e||f<d){if(f===c)return f;this.textAreaBox.dumpError(b+" in "+a+" of MazeConfig.ini must be in the range "+d+" to "+e+". "+g+" Using default values.");f=c}return f};if(null==TextAreaBox||"object"!=typeof TextAreaBox)var TextAreaBox={};TextAreaBox=function(a,b,c,d,e,g){this.context=a;this.backGroundClrStr=b;this.origTextClrStr=this.textClrStr=c;this.leftStartPoint=d;this.width=e;this.height=g;this.displayText="";this.clear()};TextAreaBox.prototype.TOP_MARGIN=12;TextAreaBox.prototype.MARGIN=1;TextAreaBox.prototype.LINE_HEIGHT=12;TextAreaBox.prototype.LINE_SEPARATOR_HEIGHT=2;TextAreaBox.prototype.FONT_STYLE="11px Arial,sans-serif";
TextAreaBox.prototype.ERROR_TEXT_COLOR="red";TextAreaBox.prototype.clear=function(){this.context.beginPath();this.context.rect(this.leftStartPoint,0,this.width,this.height);this.context.closePath();this.context.fillStyle=this.backGroundClrStr;this.context.fill();this.context.stroke()};TextAreaBox.prototype.setTextClr=function(a){this.textClrStr=a};
TextAreaBox.prototype.setDisplayText=function(a){this.displayText=a.replace(/(\r)/gm,"");this.context.font=TextAreaBox.prototype.FONT_STYLE;this.context.fillStyle=this.textClrStr;this.displayText=this.wrapLines(this.displayText,this.width-this.leftStartPoint)};
TextAreaBox.prototype.render=function(){this.context.font=TextAreaBox.prototype.FONT_STYLE;this.context.fillStyle=this.textClrStr;var a=this.displayText.split(/\r\n|\r|\n/),b=this.TOP_MARGIN,c=this;a.forEach(function(a){c.context.fillText(a,c.leftStartPoint+c.MARGIN,b);b=b+c.LINE_HEIGHT+c.LINE_SEPARATOR_HEIGHT})};TextAreaBox.prototype.dumpText=function(a){this.clear();this.setTextClr(this.origTextClrStr);this.setDisplayText(a);this.render()};
TextAreaBox.prototype.dumpError=function(a){this.clear();this.setTextClr(TextAreaBox.prototype.ERROR_TEXT_COLOR);this.setDisplayText(a);console.log(a);this.render()};TextAreaBox.prototype.wrapLines=function(a,b){var c=this,d="";a.split(/\r\n|\r|\n/).forEach(function(a){var b="",f="";a.split(" ").forEach(function(a){c.context.measureText(""+b+f+a).width<c.width-(c.MARGIN+c.MARGIN)?b=""+b+f+a:(d=""+d+b+"\n",b=a);f=" "});d=""+d+b+"\n"});return d};if(null==Trap||"object"!=typeof Trap)var Trap={};Trap=function(){this.bottomSide=this.topSide=this.rightSide=this.leftSide=0;this.usingDest=!1;this.gotoDest=0;this.usingOverlay=!1;this.overlayFile="";this.overlayPixels=null;this.usingSound=!1;this.soundFile=""};Trap.prototype.insideThisTrap=function(a,b){return a>=this.leftSide&&a<=this.rightSide&&b>=this.topSide&&b<=this.bottomSide};if(null==Trig||"object"!=typeof Trig)var Trig={};Trig=function(){this.createTables()};Trig.prototype.ANGLE60=MazeGlobals.PROJECTIONPLANEWIDTH;Trig.prototype.ANGLE30=Math.round(Trig.prototype.ANGLE60/2);Trig.prototype.ANGLE90=Math.round(3*Trig.prototype.ANGLE30);Trig.prototype.ANGLE180=Math.round(2*Trig.prototype.ANGLE90);Trig.prototype.ANGLE270=Math.round(3*Trig.prototype.ANGLE90);Trig.prototype.ANGLE360=Math.round(6*Trig.prototype.ANGLE60);Trig.prototype.ANGLE0=0;
Trig.prototype.ANGLE5=Math.round(Trig.prototype.ANGLE30/6);Trig.prototype.ANGLE10=2*Trig.prototype.ANGLE5;Trig.prototype.ANGLE45=Trig.prototype.ANGLE5+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10+Trig.prototype.ANGLE10;Trig.prototype.ANGLE135=Trig.prototype.ANGLE90+Trig.prototype.ANGLE45;Trig.prototype.ANGLE225=Trig.prototype.ANGLE180+Trig.prototype.ANGLE45;Trig.prototype.ANGLE315=Trig.prototype.ANGLE270+Trig.prototype.ANGLE45;
Trig.prototype.ANGLE85=Trig.prototype.ANGLE90-Trig.prototype.ANGLE5;Trig.prototype.ANGLE95=Trig.prototype.ANGLE90+Trig.prototype.ANGLE5;Trig.prototype.ANGLE265=Trig.prototype.ANGLE270-Trig.prototype.ANGLE5;Trig.prototype.ANGLE275=Trig.prototype.ANGLE270+Trig.prototype.ANGLE5;Trig.prototype.ANGLE355=Trig.prototype.ANGLE360-Trig.prototype.ANGLE5;Trig.prototype.ANGLE175=Trig.prototype.ANGLE180-Trig.prototype.ANGLE5;Trig.prototype.ANGLE185=Trig.prototype.ANGLE180+Trig.prototype.ANGLE5;
Trig.prototype.sinTable=[];Trig.prototype.iSinTable=[];Trig.prototype.cosTable=[];Trig.prototype.iCosTable=[];Trig.prototype.tanTable=[];Trig.prototype.iTanTable=[];Trig.prototype.fishTable=[];Trig.prototype.xStepTable=[];Trig.prototype.yStepTable=[];
Trig.prototype.createTables=function(){var a=0,b=0;this.sinTable=Array(this.ANGLE360+1);this.iSinTable=Array(this.ANGLE360+1);this.cosTable=Array(this.ANGLE360+1);this.iCosTable=Array(this.ANGLE360+1);this.tanTable=Array(this.ANGLE360+1);this.iTanTable=Array(this.ANGLE360+1);this.fishTable=Array(this.ANGLE60+1);this.xStepTable=Array(this.ANGLE360+1);this.yStepTable=Array(this.ANGLE360+1);for(a=0;a<=this.ANGLE360;a++)b=this.arcToRad(a)+1E-4,this.sinTable[a]=Math.sin(b),this.iSinTable[a]=1/this.sinTable[a],
this.cosTable[a]=Math.cos(b),this.iCosTable[a]=1/this.cosTable[a],this.tanTable[a]=Math.tan(b),this.iTanTable[a]=1/this.tanTable[a],a>=this.ANGLE90&&a<this.ANGLE270?(this.xStepTable[a]=1*MazeGlobals.TILE_SIZE/this.tanTable[a],0<this.xStepTable[a]&&(this.xStepTable[a]=-this.xStepTable[a])):(this.xStepTable[a]=1*MazeGlobals.TILE_SIZE/this.tanTable[a],0>this.xStepTable[a]&&(this.xStepTable[a]=-this.xStepTable[a])),a>=this.ANGLE0&&a<this.ANGLE180?(this.yStepTable[a]=1*MazeGlobals.TILE_SIZE*this.tanTable[a],
0>this.yStepTable[a]&&(this.yStepTable[a]=-this.yStepTable[a])):(this.yStepTable[a]=1*MazeGlobals.TILE_SIZE*this.tanTable[a],0<this.yStepTable[a]&&(this.yStepTable[a]=-this.yStepTable[a]));for(a=-this.ANGLE30;a<=this.ANGLE30;a++)b=this.arcToRad(a),this.fishTable[a+this.ANGLE30]=1/Math.cos(b)};Trig.prototype.arcToRad=function(a){return 1*a*Math.PI/this.ANGLE180};Trig.degreesToMazeAngleUnits=function(a){return~~(MazeGlobals.PROJECTIONPLANEWIDTH*a/60)};function WallHitItem(a,b,c,d){this.hitType=a;this.gridLine=b;this.intersection=c;this.castArc=d}WallHitItem.prototype.HORIZ_HIT=0;WallHitItem.prototype.VERT_HIT=1;WallHitItem.prototype.TOP_SIDE_HIT=0;WallHitItem.prototype.RIGHT_SIDE_HIT=1;WallHitItem.prototype.BOTTOM_SIDE_HIT=2;WallHitItem.prototype.LEFT_SIDE_HIT=3;WallHitItem.prototype.gridLine=0;WallHitItem.prototype.intersection=0;WallHitItem.prototype.hitType=this.HORIZ_HIT;WallHitItem.prototype.hitSide=this.TOP_SIDE_HIT;
WallHitItem.prototype.offTheMap=!1;WallHitItem.prototype.distToItem=0;WallHitItem.prototype.xGridIndex=0;WallHitItem.prototype.yGridIndex=0;WallHitItem.prototype.mapPos=0;WallHitItem.prototype.castArc=0;WallHitItem.prototype.isHorizHit=function(){return this.hitType==this.HORIZ_HIT};WallHitItem.prototype.isVertHit=function(){return this.hitType==this.VERT_HIT};function determineClosestHit(a,b){return b.offTheMap&&a.offTheMap||b.offTheMap?a:a.offTheMap?b:a.distToItem<b.distToItem?a:b}
WallHitItem.prototype.calcAndSetMapPos=function(a){this.hitType==this.HORIZ_HIT?(this.xGridIndex=~~(this.intersection/MazeGlobals.TILE_SIZE),this.yGridIndex=this.gridLine>>MazeGlobals.TILE_SIZE_SHIFT):(this.xGridIndex=this.gridLine>>MazeGlobals.TILE_SIZE_SHIFT,this.yGridIndex=~~(this.intersection/MazeGlobals.TILE_SIZE));return this.mapPos=a.convertPointToMapPos(this.xGridIndex,this.yGridIndex)};
WallHitItem.prototype.calcAndSetOffTheMap=function(a){if(this.xGridIndex>=a.mapWidth||this.yGridIndex>=a.mapHeight||0>this.xGridIndex||0>this.yGridIndex)this.distToItem=Number.MAX_VALUE,this.offTheMap=!0;return this.offTheMap};
